//! Init — proto-OS-service.
//!
//! The kernel spawns only init. Init reads a device manifest from the kernel
//! via channel shared memory, then spawns and orchestrates all other userspace
//! processes: virtio drivers, compositor, etc.
//!
//! This is the microkernel pattern: kernel provides mechanism, init provides
//! policy. Matches Fuchsia's component_manager, seL4's root task, QNX's procnto.
//!
//! # Kernel channel shared page layout (device manifest)
//!
//! ```text
//! offset 0:  device_count (u32)
//! offset 4:  _padding     (u32)
//! offset 8:  device[0]: { pa: u64, irq: u32, device_id: u32 }  (16 bytes)
//! offset 24: device[1]: ...
//! ```
//!
//! # GPU driver channel shared page layout
//!
//! ```text
//! offset 0:  mmio_pa    (u64)
//! offset 8:  irq        (u32)
//! offset 16: fb_pa      (u64) — framebuffer physical address
//! offset 24: fb_width   (u32)
//! offset 28: fb_height  (u32)
//! ```
//!
//! # Compositor channel shared page layout
//!
//! ```text
//! offset 0:  fb_va      (u64) — framebuffer VA in compositor's address space
//! offset 8:  fb_width   (u32)
//! offset 12: fb_height  (u32)
//! offset 16: fb_stride  (u32)
//! offset 20: fb_size    (u32)
//! ```

#![no_std]
#![no_main]

// ELF binaries for all processes that init can spawn.
// Generated by build.rs and included via env var at compile time.
include!(env!("INIT_EMBEDDED_RS"));

/// Channel shared memory base. The kernel's channel is at page 0.
/// Channels created by init are at subsequent pages.
const CHANNEL_SHM_BASE: usize = 0x4000_0000;
/// Framebuffer dimensions (matches QEMU virtio-gpu default).
const FB_WIDTH: u32 = 1024;
const FB_HEIGHT: u32 = 768;
const FB_BPP: u32 = 4;
const FB_STRIDE: u32 = FB_WIDTH * FB_BPP;
const FB_SIZE: u32 = FB_STRIDE * FB_HEIGHT;
/// Virtio device IDs (must match kernel probe).
const VIRTIO_DEVICE_BLK: u32 = 2;
const VIRTIO_DEVICE_CONSOLE: u32 = 3;
const VIRTIO_DEVICE_GPU: u32 = 16;

/// Compute the VA of channel shared page N in init's address space.
/// Page 0 = kernel channel, page 1+ = channels created by init.
fn channel_shm_va(page_index: usize) -> usize {
    CHANNEL_SHM_BASE + page_index * 4096
}
fn print_u32(mut n: u32) {
    if n == 0 {
        sys::write(b"0");

        return;
    }

    let mut buf = [0u8; 10];
    let mut i = 10;

    while n > 0 {
        i -= 1;
        buf[i] = b'0' + (n % 10) as u8;
        n /= 10;
    }

    sys::write(&buf[i..]);
}
/// Set up the display pipeline: allocate framebuffer, spawn compositor,
/// wait for it to draw, then start the GPU driver to present.
fn setup_display_pipeline(
    gpu_proc: u8,
    gpu_page: usize,
    gpu_pa: u64,
    gpu_irq: u32,
    next_page: &mut usize,
) {
    sys::write(b"     setting up display pipeline\n");

    // Allocate framebuffer via DMA.
    let fb_bytes = FB_SIZE as usize;
    let fb_pages = (fb_bytes + 4095) / 4096;
    let fb_order = (fb_pages.next_power_of_two().trailing_zeros()) as u32;
    let mut fb_pa_out: u64 = 0;
    let fb_va = sys::dma_alloc(fb_order, &mut fb_pa_out);

    if fb_va < 0 {
        sys::write(b"init: dma_alloc (framebuffer) failed\n");
        sys::exit();
    }

    // Zero the framebuffer.
    let fb_alloc_bytes = (1usize << fb_order) * 4096;

    unsafe { core::ptr::write_bytes(fb_va as *mut u8, 0, fb_alloc_bytes) };

    sys::write(b"     framebuffer: ");

    print_u32(FB_WIDTH);

    sys::write(b"x");

    print_u32(FB_HEIGHT);

    sys::write(b" (");

    print_u32(fb_alloc_bytes as u32 / 1024);

    sys::write(b" KiB)\n");

    // Write GPU device info + framebuffer PA to GPU driver's channel page.
    let gpu_shm = channel_shm_va(gpu_page) as *mut u8;

    unsafe {
        core::ptr::write_volatile(gpu_shm as *mut u64, gpu_pa);
        core::ptr::write_volatile(gpu_shm.add(8) as *mut u32, gpu_irq);
        core::ptr::write_volatile(gpu_shm.add(16) as *mut u64, fb_pa_out);
        core::ptr::write_volatile(gpu_shm.add(24) as *mut u32, FB_WIDTH);
        core::ptr::write_volatile(gpu_shm.add(28) as *mut u32, FB_HEIGHT);
    }

    // Spawn compositor.
    let (comp_proc, comp_ch, comp_page) = match spawn_with_channel(COMPOSITOR_ELF, next_page) {
        Some(v) => v,
        None => {
            sys::write(b"init: failed to spawn compositor\n");
            sys::exit();
        }
    };
    // Share framebuffer memory with compositor.
    let fb_page_count = fb_alloc_bytes as u64 / 4096;
    let comp_fb_va = sys::memory_share(comp_proc, fb_pa_out, fb_page_count);

    if comp_fb_va < 0 {
        sys::write(b"init: memory_share (compositor) failed\n");
        sys::exit();
    }

    // Write compositor info to its channel shared page.
    let comp_shm = channel_shm_va(comp_page) as *mut u8;

    unsafe {
        core::ptr::write_volatile(comp_shm as *mut u64, comp_fb_va as u64);
        core::ptr::write_volatile(comp_shm.add(8) as *mut u32, FB_WIDTH);
        core::ptr::write_volatile(comp_shm.add(12) as *mut u32, FB_HEIGHT);
        core::ptr::write_volatile(comp_shm.add(16) as *mut u32, FB_STRIDE);
        core::ptr::write_volatile(comp_shm.add(20) as *mut u32, FB_SIZE);
    }

    // Start compositor and wait for it to draw.
    sys::process_start(comp_proc);
    sys::write(b"     compositor started, waiting\n");
    sys::wait(&[comp_ch], u64::MAX);
    sys::write(b"     compositor done, starting gpu driver\n");
    // Start GPU driver to present the framebuffer.
    sys::process_start(gpu_proc);
    // Wait for GPU driver's process to exit.
    sys::wait(&[gpu_proc], u64::MAX);
    sys::write(b"     display pipeline complete\n");
}
/// Spawn a suspended process, create a channel to it, and send one endpoint.
///
/// Returns (process_handle, init_channel_handle, shm_page_index) on success.
/// The child receives endpoint B at CHANNEL_SHM_BASE in its address space.
/// Init retains endpoint A; the shared page is at channel_shm_va(page_index).
fn spawn_with_channel(elf: &[u8], next_page: &mut usize) -> Option<(u8, u8, usize)> {
    sys::write(b"       process_create\xE2\x80\xA6");

    let proc_handle = sys::process_create(elf.as_ptr(), elf.len());

    if proc_handle < 0 {
        sys::write(b" FAILED\n");

        return None;
    }

    sys::write(b" ok\n");

    let proc_handle = proc_handle as u8;

    sys::write(b"       channel_create\xE2\x80\xA6");

    let ch = sys::channel_create();

    if ch < 0 {
        sys::write(b" FAILED\n");

        return None;
    }

    sys::write(b" ok\n");

    let ch_a = (ch & 0xFF) as u8;
    let ch_b = ((ch >> 8) & 0xFF) as u8;

    sys::write(b"       handle_send\xE2\x80\xA6");

    let ret = sys::handle_send(proc_handle, ch_b);

    if ret < 0 {
        sys::write(b" FAILED\n");

        return None;
    }

    sys::write(b" ok\n");

    let page_idx = *next_page;

    *next_page += 1;

    Some((proc_handle, ch_a, page_idx))
}

#[unsafe(no_mangle)]
pub extern "C" fn _start() -> ! {
    sys::write(b"  \xF0\x9F\x94\xA7 init - proto-os-service starting\n");

    // Page 0 in channel SHM = kernel's channel (device manifest).
    let kernel_shm = CHANNEL_SHM_BASE as *const u8;
    let device_count = unsafe { core::ptr::read_volatile(kernel_shm as *const u32) };

    sys::write(b"     ");

    print_u32(device_count);

    sys::write(b" devices in manifest\n");

    // Track channel SHM page allocation (0 = kernel, 1+ = ours).
    let mut next_page: usize = 1;
    // Saved GPU state for Phase 2.
    // (proc, ch, page, pa, irq)
    let mut gpu: Option<(u8, u8, usize, u64, u32)> = None;
    // Phase 1: Spawn a driver for each device in the manifest.
    let actual = if device_count > 8 { 8 } else { device_count };

    for i in 0..actual as usize {
        let base = unsafe { kernel_shm.add(8 + i * 16) };
        let dev_pa = unsafe { core::ptr::read_volatile(base as *const u64) };
        let dev_irq = unsafe { core::ptr::read_volatile(base.add(8) as *const u32) };
        let dev_id = unsafe { core::ptr::read_volatile(base.add(12) as *const u32) };

        sys::write(b"     device ");

        print_u32(i as u32);

        sys::write(b": id=");

        print_u32(dev_id);

        sys::write(b"\n");

        let elf: &[u8] = match dev_id {
            VIRTIO_DEVICE_BLK => VIRTIO_BLK_ELF,
            VIRTIO_DEVICE_CONSOLE => VIRTIO_CONSOLE_ELF,
            VIRTIO_DEVICE_GPU => VIRTIO_GPU_ELF,
            _ => {
                sys::write(b"     skipping unknown device id=");
                print_u32(dev_id);
                sys::write(b"\n");
                continue;
            }
        };

        sys::write(b"     spawning driver (elf ");

        print_u32(elf.len() as u32);

        sys::write(b" bytes)\n");

        let (proc_h, ch_h, page_idx) = match spawn_with_channel(elf, &mut next_page) {
            Some(v) => v,
            None => continue,
        };

        if dev_id == VIRTIO_DEVICE_GPU {
            // Defer GPU startup — need framebuffer first.
            gpu = Some((proc_h, ch_h, page_idx, dev_pa, dev_irq));
        } else {
            // Write device info and start immediately.
            let shm = channel_shm_va(page_idx) as *mut u8;

            unsafe {
                core::ptr::write_volatile(shm as *mut u64, dev_pa);
                core::ptr::write_volatile(shm.add(8) as *mut u32, dev_irq);
            }

            sys::process_start(proc_h);

            let name = match dev_id {
                VIRTIO_DEVICE_BLK => "blk",
                VIRTIO_DEVICE_CONSOLE => "console",
                _ => "?",
            };

            sys::write(b"     spawned driver: ");
            sys::write(name.as_bytes());
            sys::write(b"\n");
        }
    }

    // Phase 2: Display pipeline (compositor → GPU driver).
    if let Some((gpu_proc, _gpu_ch, gpu_page, gpu_pa, gpu_irq)) = gpu {
        setup_display_pipeline(gpu_proc, gpu_page, gpu_pa, gpu_irq, &mut next_page);
    } else {
        sys::write(b"     no gpu found\n");
    }

    sys::write(b"  \xF0\x9F\x94\xA7 init - done\n");
    sys::exit();
}
