//! Init — proto-OS-service.
//!
//! The kernel spawns only init. Init reads a device manifest from the kernel
//! via channel shared memory, then spawns and orchestrates all other userspace
//! processes: virtio drivers, compositor, etc.
//!
//! This is the microkernel pattern: kernel provides mechanism, init provides
//! policy. Matches Fuchsia's component_manager, seL4's root task, QNX's procnto.
//!
//! # IPC topology
//!
//! Init creates three kinds of channels:
//!
//! 1. **Config channels** (init ↔ child) — one per child process. Init sends
//!    configuration as the first ring buffer message before starting the child.
//!
//! 2. **Input channel** (input driver → compositor) — carries keyboard events.
//!    Init creates the channel, sends endpoint A to the input driver and
//!    endpoint B to the compositor. The driver produces, compositor consumes.
//!
//! 3. **Present channel** (compositor → GPU driver) — carries frame present
//!    commands. Compositor produces, GPU driver consumes.
//!
//! # Kernel channel (raw bytes, not ring buffer)
//!
//! The kernel writes the device manifest as raw bytes before starting init.
//! The kernel doesn't use the ipc library — it writes directly to the shared
//! page. This is the only non-ring-buffer channel in the system.
//!
//! ```text
//! offset 0:  device_count (u32)
//! offset 4:  _padding     (u32)
//! offset 8:  device[0]: { pa: u64, irq: u32, device_id: u32 }  (16 bytes)
//! offset 24: device[1]: ...
//! ```

#![no_std]
#![no_main]

extern crate scene;

// ELF binaries for all processes that init can spawn.
// Generated by build.rs and included via env var at compile time.
include!(env!("INIT_EMBEDDED_RS"));

/// Channel shared memory base. The kernel's channel is at page 0.
/// Channels created by init are at subsequent 2-page pairs.
use protocol::compose::{
    CompositorConfig, ImageConfig, RtcConfig, MSG_COMPOSITOR_CONFIG, MSG_IMAGE_CONFIG,
    MSG_RTC_CONFIG,
};
use protocol::{
    core_config::{CoreConfig, MSG_CORE_CONFIG},
    device::{DeviceConfig, MSG_DEVICE_CONFIG},
    editor::{EditorConfig, MSG_EDITOR_CONFIG},
    fs::{MSG_FS_READ_REQUEST, MSG_FS_READ_RESPONSE},
    gpu::{
        DisplayInfoMsg, FbPaChunk, GpuConfig, MSG_DISPLAY_INFO, MSG_FB_PA_CHUNK, MSG_GPU_CONFIG,
        MSG_GPU_READY,
    },
};

/// Bytes per pixel (BGRA8888).
const FB_BPP: u32 = 4;
/// Virtio device IDs (must match kernel probe).
const VIRTIO_DEVICE_BLK: u32 = 2;
const VIRTIO_DEVICE_CONSOLE: u32 = 3;
const VIRTIO_DEVICE_GPU: u32 = 16;
const VIRTIO_DEVICE_INPUT: u32 = 18;
const VIRTIO_DEVICE_9P: u32 = 9;
/// Virtio MMIO register offsets for feature probing.
const MMIO_DEVICE_FEATURES: usize = 0x010;
const MMIO_DEVICE_FEATURES_SEL: usize = 0x014;
/// Pseudo device ID for the PL031 RTC (matches kernel's DEVICE_ID_PL031_RTC).
const DEVICE_PL031_RTC: u32 = 200;
/// Document buffer: 1 page. First 64 bytes = header, rest = content.
const DOC_BUF_PAGES: u64 = 1;
const DOC_BUF_HEADER: u32 = 64;
const DOC_BUF_CAPACITY: u32 = (DOC_BUF_PAGES as u32 * 4096) - DOC_BUF_HEADER;
/// Maximum number of virtio-input devices we can handle (keyboard + tablet).
const MAX_INPUT_DEVICES: usize = 4;

fn channel_shm_va(channel_index: usize) -> usize {
    protocol::channel_shm_va(channel_index)
}
/// Format a u32 into a buffer, returning the number of bytes written.
fn format_u32(mut n: u32, buf: &mut [u8]) -> usize {
    if n == 0 {
        buf[0] = b'0';
        return 1;
    }

    let mut tmp = [0u8; 10];
    let mut i = 10;

    while n > 0 {
        i -= 1;
        tmp[i] = b'0' + (n % 10) as u8;
        n /= 10;
    }

    let len = 10 - i;

    buf[..len].copy_from_slice(&tmp[i..]);

    len
}
/// Create an IPC channel for a given channel index. Init is always endpoint 0.
fn init_channel(channel_index: usize) -> ipc::Channel {
    let ch = unsafe { ipc::Channel::from_base(channel_shm_va(channel_index), ipc::PAGE_SIZE, 0) };

    ch.init();

    ch
}
fn print_u32(mut n: u32) {
    if n == 0 {
        sys::print(b"0");

        return;
    }

    let mut buf = [0u8; 10];
    let mut i = 10;

    while n > 0 {
        i -= 1;
        buf[i] = b'0' + (n % 10) as u8;
        n /= 10;
    }

    sys::print(&buf[i..]);
}
/// Probe a virtio-gpu device for VIRTIO_GPU_F_VIRGL (bit 0) support.
///
/// Maps the device MMIO region, reads the feature register, and checks
/// whether the device advertises 3D virgl capability. This determines
/// whether init spawns virgil-render (GPU-accelerated) or the CPU
/// fallback pipeline (compositor + virtio-gpu 2D).
///
/// # Safety
/// Reads two MMIO registers (DeviceFeaturesSel, DeviceFeatures).
/// Does not change device state — safe to call before driver negotiation.
fn probe_virgl(gpu_pa: u64) -> bool {
    let page_pa = gpu_pa & !0xFFF;
    let page_offset = (gpu_pa & 0xFFF) as usize;

    let va = match sys::device_map(page_pa, 0x1000) {
        Ok(v) => v,
        Err(_) => {
            sys::print(b"     virgl probe: device_map failed, assuming no virgl\n");
            return false;
        }
    };

    let base = va + page_offset;

    // SAFETY: MMIO register reads. DeviceFeaturesSel at +0x14 selects which
    // 32-bit page of features to read. DeviceFeatures at +0x10 returns the
    // selected page. Writing sel=0 selects bits [31:0]. These are read-only
    // probes that don't alter device state.
    unsafe {
        core::ptr::write_volatile((base + MMIO_DEVICE_FEATURES_SEL) as *mut u32, 0);
    }

    let features = unsafe { core::ptr::read_volatile((base + MMIO_DEVICE_FEATURES) as *const u32) };

    // VIRTIO_GPU_F_VIRGL = bit 0
    let has_virgl = features & 1 != 0;

    if has_virgl {
        sys::print(b"     virgl probe: 3D support detected\n");
    } else {
        sys::print(b"     virgl probe: no 3D support, using CPU fallback\n");
    }

    has_virgl
}

fn setup_virgl_pipeline(
    gpu_proc: u8,
    gpu_ch_handle: u8,
    gpu_channel_idx: usize,
    gpu_pa: u64,
    gpu_irq: u32,
    input_devices: &[(u8, usize, u64, u32)], // slice of (proc, ch_idx, pa, irq)
    font_buf: Option<(u64, u32, u32, u32, u32)>, // (pa, mono_len, prop_len, png_offset, png_len)
    rtc_pa: u64,                             // PL031 RTC physical address (0 = not found)
    next_channel: &mut usize,
) {
    sys::print(b"     setting up virgl pipeline\n");

    // -----------------------------------------------------------------------
    // Phase 1: Allocate scene graph + doc buffer (no display dependency).
    // These must be shared BEFORE starting virgil-render.
    // -----------------------------------------------------------------------
    let scene_size = scene::TRIPLE_SCENE_SIZE;
    let scene_pages_needed = (scene_size + 4095) / 4096;
    let scene_order = (scene_pages_needed.next_power_of_two().trailing_zeros()) as u32;
    let scene_alloc_bytes = (1usize << scene_order) * 4096;
    let mut scene_pa: u64 = 0;
    let _scene_va = sys::dma_alloc(scene_order, &mut scene_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (scene graph) failed\n");
        sys::exit();
    });

    unsafe { core::ptr::write_bytes(_scene_va as *mut u8, 0, scene_alloc_bytes) };

    sys::print(b"     scene graph: shared memory allocated\n");

    let scene_page_count = scene_alloc_bytes as u64 / 4096;

    // Document buffer (1 page).
    let mut doc_pa: u64 = 0;
    let _doc_va = sys::dma_alloc(0, &mut doc_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (doc buffer) failed\n");
        sys::exit();
    });

    unsafe { core::ptr::write_bytes(_doc_va as *mut u8, 0, 4096) };

    sys::print(b"     document buffer: 4 KiB shared\n");

    // Unpack font buffer info.
    let (font_pa_val, mono_font_len, prop_font_len, png_offset, png_len) =
        if let Some((pa, mono, prop, png_off, png_l)) = font_buf {
            (pa, mono, prop, png_off, png_l)
        } else {
            (0u64, 0u32, 0u32, 0u32, 0u32)
        };
    let font_total_len = mono_font_len + prop_font_len + png_len;
    let font_pages = if font_total_len > 0 {
        ((font_total_len as u64) + 4095) / 4096
    } else {
        0
    };

    // -----------------------------------------------------------------------
    // Phase 2: Create core→virgil-render scene update channel.
    // -----------------------------------------------------------------------
    sys::print(b"     creating core\xE2\x86\x92virgil-render channel\n");

    let (cv_a, cv_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (core-virgl) failed\n");
        sys::exit();
    });

    *next_channel += 1;

    // -----------------------------------------------------------------------
    // Phase 3: Share memory with virgil-render BEFORE starting it.
    // memory_share only works on unstarted processes.
    // -----------------------------------------------------------------------

    // Share scene graph with virgil-render (for reading).
    let virgl_scene_va = sys::memory_share(gpu_proc, scene_pa, scene_page_count, false)
        .unwrap_or_else(|_| {
            sys::print(b"init: memory_share (virgl scene) failed\n");
            sys::exit();
        });

    // Share font data with virgil-render (future: glyph atlas).
    let virgl_font_va = if font_pages > 0 {
        sys::memory_share(gpu_proc, font_pa_val, font_pages, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (virgl font) failed\n");
            sys::exit();
        }) as u64
    } else {
        0u64
    };

    // Send scene update channel endpoint B to virgil-render (handle 1).
    sys::handle_send(gpu_proc, cv_b).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-virgl B) failed\n");
        sys::exit();
    });

    // -----------------------------------------------------------------------
    // Phase 4: Start virgil-render for display query.
    // Send device config first, then start.
    // -----------------------------------------------------------------------
    let gpu_ch = init_channel(gpu_channel_idx);
    let dev_config = DeviceConfig {
        mmio_pa: gpu_pa,
        irq: gpu_irq,
        _pad: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &dev_config) };

    gpu_ch.send(&msg);

    sys::print(b"     starting virgil-render (display query)\n");

    let _ = sys::process_start(gpu_proc);

    // Wait for display info from virgil-render.
    sys::print(b"     waiting for display info\n");

    let mut resp_msg = ipc::Message::new(0);

    loop {
        let _ = sys::wait(&[gpu_ch_handle], u64::MAX);

        if gpu_ch.try_recv(&mut resp_msg) && resp_msg.msg_type == MSG_DISPLAY_INFO {
            break;
        }
    }

    let display_info: DisplayInfoMsg = unsafe { resp_msg.payload_as() };
    let fb_width = display_info.width;
    let fb_height = display_info.height;

    // Compute scale factor.
    let scale_factor: f32 = if fb_width >= 2048 { 2.0 } else { 1.0 };
    let logical_w = (fb_width as f32 / scale_factor) as u32;
    let logical_h = (fb_height as f32 / scale_factor) as u32;

    {
        let mut buf = [0u8; 40];
        let prefix = b"     display resolution: ";

        buf[..prefix.len()].copy_from_slice(prefix);

        let mut pos = prefix.len();

        pos += format_u32(fb_width, &mut buf[pos..]);
        buf[pos] = b'x';
        pos += 1;
        pos += format_u32(fb_height, &mut buf[pos..]);
        buf[pos] = b'\n';
        pos += 1;

        sys::print(&buf[..pos]);
    }

    // -----------------------------------------------------------------------
    // Phase 5: Send GPU config (virgil-render drains FB PA chunks).
    // We still send GpuConfig + chunks so virgil-render's init_handshake works.
    // -----------------------------------------------------------------------
    let gpu_config = GpuConfig {
        mmio_pa: gpu_pa,
        irq: gpu_irq,
        _pad: 0,
        fb_width,
        fb_height,
        fb_size: fb_width * fb_height * FB_BPP,
        chunks_per_buf: 0, // no framebuffer chunks for virgl
        chunk_order: 0,
        _pad2: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_GPU_CONFIG, &gpu_config) };

    gpu_ch.send(&msg);

    let _ = sys::channel_signal(gpu_ch_handle);

    // Wait for GPU_READY.
    loop {
        let _ = sys::wait(&[gpu_ch_handle], u64::MAX);

        if gpu_ch.try_recv(&mut resp_msg) && resp_msg.msg_type == MSG_GPU_READY {
            break;
        }
    }

    // -----------------------------------------------------------------------
    // Phase 6: Send render config (CompositorConfig) to virgil-render.
    // Reuse CompositorConfig struct: scene_va, font_va, font_len, scale.
    // virgil-render ignores fb_va/fb_va2 fields.
    // -----------------------------------------------------------------------
    let render_config = CompositorConfig {
        fb_va: 0, // unused by virgil-render
        fb_va2: 0,
        scene_va: virgl_scene_va as u64,
        mono_font_va: virgl_font_va,
        fb_width,
        fb_height,
        mono_font_len,
        prop_font_len,
        scale_factor,
        frame_rate: 60,
        _pad: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_COMPOSITOR_CONFIG, &render_config) };

    gpu_ch.send(&msg);

    let _ = sys::channel_signal(gpu_ch_handle);

    sys::print(b"     render config sent to virgil-render\n");

    // -----------------------------------------------------------------------
    // Phase 7: Spawn core process.
    // -----------------------------------------------------------------------
    let (core_proc, _core_ch_handle, core_channel_idx) =
        match spawn_with_channel(CORE_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn core\n");
                sys::exit();
            }
        };
    // Share document buffer with core (read-write).
    let core_doc_va =
        sys::memory_share(core_proc, doc_pa, DOC_BUF_PAGES, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (core doc) failed\n");
            sys::exit();
        });
    // Share scene graph with core (read-write).
    let core_scene_va = sys::memory_share(core_proc, scene_pa, scene_page_count, false)
        .unwrap_or_else(|_| {
            sys::print(b"init: memory_share (core scene) failed\n");
            sys::exit();
        });
    // Share font data with core (read-only).
    let core_font_va = if font_pages > 0 {
        sys::memory_share(core_proc, font_pa_val, font_pages, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (core font) failed\n");
            sys::exit();
        }) as u64
    } else {
        0u64
    };
    // Send core config.
    let core_ch = init_channel(core_channel_idx);
    let core_config = CoreConfig {
        doc_va: core_doc_va as u64,
        scene_va: core_scene_va as u64,
        mono_font_va: core_font_va,
        fb_width: logical_w,
        fb_height: logical_h,
        doc_capacity: DOC_BUF_CAPACITY,
        mono_font_len,
        prop_font_len,
        _pad: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_CORE_CONFIG, &core_config) };

    core_ch.send(&msg);

    // Send image config to core (for has_image detection).
    if png_len > 0 {
        let image_va = core_font_va + png_offset as u64;
        let img_config = ImageConfig {
            image_va,
            image_len: png_len,
            _pad: 0,
        };
        let img_msg = unsafe { ipc::Message::from_payload(MSG_IMAGE_CONFIG, &img_config) };

        core_ch.send(&img_msg);
    }

    // Send RTC config to core.
    if rtc_pa != 0 {
        let rtc_config = RtcConfig { mmio_pa: rtc_pa };
        let rtc_msg = unsafe { ipc::Message::from_payload(MSG_RTC_CONFIG, &rtc_config) };

        core_ch.send(&rtc_msg);

        sys::print(b"     rtc config sent to core\n");
    }

    // -----------------------------------------------------------------------
    // Phase 8: Cross-process channels.
    //
    // Core handle layout:
    //   handle 1 = first input (keyboard)
    //   handle 2 = core → virgil-render (scene update)
    //   handle 3 = core ↔ editor
    //   handle 4+ = additional input devices
    // -----------------------------------------------------------------------

    // Input → Core channel (keyboard events).
    if !input_devices.is_empty() {
        let (input_proc_handle, input_ch_idx, input_pa, input_irq) = input_devices[0];

        sys::print(b"     creating input\xE2\x86\x92core channel\n");

        let (ic_a, ic_b) = sys::channel_create().unwrap_or_else(|_| {
            sys::print(b"init: channel_create (input-core) failed\n");
            sys::exit();
        });

        *next_channel += 1;

        sys::handle_send(input_proc_handle, ic_a).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-core A) failed\n");
            sys::exit();
        });
        // Send to core (handle 1 in core).
        sys::handle_send(core_proc, ic_b).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-core B) failed\n");
            sys::exit();
        });

        let input_ch = init_channel(input_ch_idx);
        let input_config = DeviceConfig {
            mmio_pa: input_pa,
            irq: input_irq,
            _pad: 0,
        };
        let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &input_config) };

        input_ch.send(&msg);

        sys::print(b"     input device 0 channel created\n");
    }

    // Core → virgil-render scene update channel.
    // Endpoint A → core (handle 2 = COMPOSITOR_HANDLE in core).
    sys::handle_send(core_proc, cv_a).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-virgl A) failed\n");
        sys::exit();
    });

    // -----------------------------------------------------------------------
    // Phase 9: Core ↔ Editor channel.
    // -----------------------------------------------------------------------
    sys::print(b"     spawning text editor\n");

    let (editor_proc, _editor_ch, editor_ch_idx) =
        match spawn_with_channel(TEXT_EDITOR_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn text editor\n");
                sys::exit();
            }
        };
    // Share document buffer with editor (read-only).
    let editor_doc_va =
        sys::memory_share(editor_proc, doc_pa, DOC_BUF_PAGES, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (editor doc) failed\n");
            sys::exit();
        });
    let editor_ch = init_channel(editor_ch_idx);
    let editor_config = EditorConfig {
        doc_va: editor_doc_va as u64,
        doc_capacity: DOC_BUF_CAPACITY,
        _pad: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_EDITOR_CONFIG, &editor_config) };

    editor_ch.send(&msg);

    sys::print(b"     creating core\xE2\x86\x94editor channel\n");

    let (ce_a, ce_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (core-editor) failed\n");
        sys::exit();
    });

    *next_channel += 1;

    // Endpoint A → core (handle 3 = EDITOR_HANDLE in core).
    sys::handle_send(core_proc, ce_a).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-editor A) failed\n");
        sys::exit();
    });
    // Endpoint B → editor (handle 1 in editor's table).
    sys::handle_send(editor_proc, ce_b).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-editor B) failed\n");
        sys::exit();
    });

    // Additional input device channels → core handle 4+.
    for i in 1..input_devices.len() {
        let (input_proc_handle, input_ch_idx, input_pa, input_irq) = input_devices[i];

        sys::print(b"     creating input\xE2\x86\x92core channel\n");

        let (ic_a, ic_b) = sys::channel_create().unwrap_or_else(|_| {
            sys::print(b"init: channel_create (input-core) failed\n");
            sys::exit();
        });

        *next_channel += 1;

        sys::handle_send(input_proc_handle, ic_a).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-core A) failed\n");
            sys::exit();
        });
        sys::handle_send(core_proc, ic_b).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-core B) failed\n");
            sys::exit();
        });

        let input_ch = init_channel(input_ch_idx);
        let input_config = DeviceConfig {
            mmio_pa: input_pa,
            irq: input_irq,
            _pad: 0,
        };
        let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &input_config) };

        input_ch.send(&msg);
    }

    // -----------------------------------------------------------------------
    // Phase 10: Start processes.
    // Input drivers first, then editor, then core.
    // virgil-render is already running (started in Phase 4).
    // No compositor to start.
    // -----------------------------------------------------------------------
    for &(input_proc_handle, _, _, _) in input_devices {
        sys::print(b"     starting input driver\n");

        let _ = sys::process_start(input_proc_handle);

        sys::yield_now();
    }

    sys::print(b"     starting text editor\n");

    let _ = sys::process_start(editor_proc);

    sys::yield_now();

    sys::print(b"     starting core\n");

    let _ = sys::process_start(core_proc);

    sys::yield_now();

    sys::print(b"     virgl pipeline running\n");
}
fn setup_display_pipeline(
    gpu_proc: u8,
    gpu_ch_handle: u8,
    gpu_channel_idx: usize,
    gpu_pa: u64,
    gpu_irq: u32,
    input_devices: &[(u8, usize, u64, u32)], // slice of (proc, ch_idx, pa, irq)
    font_buf: Option<(u64, u32, u32, u32, u32)>, // (pa, mono_len, prop_len, png_offset, png_len)
    rtc_pa: u64,                             // PL031 RTC physical address (0 = not found)
    next_channel: &mut usize,
) {
    sys::print(b"     setting up display pipeline\n");

    // -----------------------------------------------------------------------
    // Phase 1: Create compositor→GPU channel BEFORE starting GPU driver.
    // handle_send only works on unstarted processes, so all handles must be
    // sent before process_start.
    // -----------------------------------------------------------------------
    sys::print(b"     creating compositor\xE2\x86\x92gpu channel\n");

    let (cg_a, cg_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (comp-gpu) failed\n");
        sys::exit();
    });

    *next_channel += 1;

    // Send present channel endpoint B to GPU driver (handle 1).
    sys::handle_send(gpu_proc, cg_b).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (comp-gpu B) failed\n");
        sys::exit();
    });

    // -----------------------------------------------------------------------
    // Phase 2: Start GPU driver for display query. Send device config first.
    // -----------------------------------------------------------------------
    let gpu_ch = init_channel(gpu_channel_idx);
    let dev_config = DeviceConfig {
        mmio_pa: gpu_pa,
        irq: gpu_irq,
        _pad: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &dev_config) };

    gpu_ch.send(&msg);

    sys::print(b"     starting gpu driver (display query)\n");

    let _ = sys::process_start(gpu_proc);

    // Wait for the GPU driver to report display dimensions.
    sys::print(b"     waiting for display info\n");

    let mut resp_msg = ipc::Message::new(0);

    loop {
        let _ = sys::wait(&[gpu_ch_handle], u64::MAX);

        if gpu_ch.try_recv(&mut resp_msg) && resp_msg.msg_type == MSG_DISPLAY_INFO {
            break;
        }
    }

    let display_info: DisplayInfoMsg = unsafe { resp_msg.payload_as() };
    let fb_width = display_info.width;
    let fb_height = display_info.height;
    let fb_stride = fb_width * FB_BPP;
    let fb_size = fb_stride * fb_height;
    // Compute fractional display scale factor from physical resolution.
    // >= 2048px wide → 2.0×, otherwise 1.0×. Matches Retina/HiDPI thresholds.
    // f32 represents 1.0, 1.25, 1.5, 1.75, 2.0 exactly.
    let scale_factor: f32 = if fb_width >= 2048 { 2.0 } else { 1.0 };
    let logical_w = (fb_width as f32 / scale_factor) as u32;
    let logical_h = (fb_height as f32 / scale_factor) as u32;

    {
        let mut buf = [0u8; 40];
        let prefix = b"     display resolution: ";

        buf[..prefix.len()].copy_from_slice(prefix);

        let mut pos = prefix.len();

        pos += format_u32(fb_width, &mut buf[pos..]);
        buf[pos] = b'x';
        pos += 1;
        pos += format_u32(fb_height, &mut buf[pos..]);
        buf[pos] = b'\n';
        pos += 1;

        sys::print(&buf[..pos]);
    }

    // -----------------------------------------------------------------------
    // Phase 3: Allocate double framebuffer using scatter-gather.
    //
    // Each buffer is allocated as many small chunks (order CHUNK_ORDER) instead
    // of one huge contiguous block. The DMA bump allocator gives contiguous VA
    // even when PAs are scattered. The GPU driver uses the PA table to build a
    // scatter-gather attach_backing command.
    // -----------------------------------------------------------------------
    const CHUNK_ORDER: u32 = 6; // 64 pages = 256 KiB per chunk
    const CHUNK_PAGES: usize = 1 << CHUNK_ORDER;
    const CHUNK_BYTES: usize = CHUNK_PAGES * 4096;

    let fb_bytes = fb_size as usize;
    let chunks_per_buf = (fb_bytes + CHUNK_BYTES - 1) / CHUNK_BYTES;
    let fb_alloc_bytes = chunks_per_buf * CHUNK_BYTES;

    // PA table: tracks chunk PAs for GPU scatter-gather and compositor sharing.
    // Max 512 chunks per buffer (64 KiB × 512 = 32 MiB, covers up to 8K).
    // Uses static to avoid blowing the 16 KiB stack (1024 × 8 = 8 KiB).
    const MAX_CHUNKS: usize = 512;
    static mut PA_TABLE_BUF: [u64; MAX_CHUNKS * 2] = [0u64; MAX_CHUNKS * 2];
    let pa_table = unsafe { &mut PA_TABLE_BUF };

    // Front buffer (buffer 0): allocate chunks, record PAs.
    let mut fb_va0: usize = 0;
    for i in 0..chunks_per_buf {
        let mut chunk_pa: u64 = 0;
        let chunk_va = sys::dma_alloc(CHUNK_ORDER, &mut chunk_pa).unwrap_or_else(|_| {
            sys::print(b"init: dma_alloc (fb0 chunk) failed\n");
            sys::exit();
        });
        if i == 0 {
            fb_va0 = chunk_va;
        }
        pa_table[i] = chunk_pa;
        unsafe { core::ptr::write_bytes(chunk_va as *mut u8, 0, CHUNK_BYTES) };
    }

    // Back buffer (buffer 1): allocate chunks, record PAs.
    let mut fb_va1: usize = 0;
    for i in 0..chunks_per_buf {
        let mut chunk_pa: u64 = 0;
        let chunk_va = sys::dma_alloc(CHUNK_ORDER, &mut chunk_pa).unwrap_or_else(|_| {
            sys::print(b"init: dma_alloc (fb1 chunk) failed\n");
            sys::exit();
        });
        if i == 0 {
            fb_va1 = chunk_va;
        }
        pa_table[chunks_per_buf + i] = chunk_pa;
        unsafe { core::ptr::write_bytes(chunk_va as *mut u8, 0, CHUNK_BYTES) };
    }

    {
        let mut buf = [0u8; 80];
        let prefix = b"     double framebuffer: ";

        buf[..prefix.len()].copy_from_slice(prefix);

        let mut pos = prefix.len();

        pos += format_u32(fb_width, &mut buf[pos..]);
        buf[pos] = b'x';
        pos += 1;
        pos += format_u32(fb_height, &mut buf[pos..]);

        let mid = b" x2 (";

        buf[pos..pos + mid.len()].copy_from_slice(mid);

        pos += mid.len();
        pos += format_u32((fb_alloc_bytes * 2) as u32 / 1024, &mut buf[pos..]);

        let mid2 = b" KiB, ";

        buf[pos..pos + mid2.len()].copy_from_slice(mid2);

        pos += mid2.len();
        pos += format_u32(chunks_per_buf as u32, &mut buf[pos..]);

        let suffix = b" chunks)\n";

        buf[pos..pos + suffix.len()].copy_from_slice(suffix);

        pos += suffix.len();

        sys::print(&buf[..pos]);
    }

    // -----------------------------------------------------------------------
    // Phase 4: Send GPU config with framebuffer info to running GPU driver.
    // -----------------------------------------------------------------------
    let gpu_config = GpuConfig {
        mmio_pa: gpu_pa,
        irq: gpu_irq,
        _pad: 0,
        fb_width,
        fb_height,
        fb_size,
        chunks_per_buf: chunks_per_buf as u16,
        chunk_order: CHUNK_ORDER as u8,
        _pad2: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_GPU_CONFIG, &gpu_config) };

    gpu_ch.send(&msg);

    // Send scatter-gather PA table entries (both buffers, 6 PAs per message).
    let total_entries = chunks_per_buf * 2;
    let mut sent = 0;
    while sent < total_entries {
        let remaining = total_entries - sent;
        let count = if remaining > 6 { 6 } else { remaining };
        let mut chunk = FbPaChunk {
            count: count as u32,
            _pad: 0,
            pas: [0u64; 6],
        };
        for j in 0..count {
            chunk.pas[j] = pa_table[sent + j];
        }
        let pa_msg = unsafe { ipc::Message::from_payload(MSG_FB_PA_CHUNK, &chunk) };
        gpu_ch.send(&pa_msg);
        sent += count;
    }

    let _ = sys::channel_signal(gpu_ch_handle);

    // Wait for the GPU driver to complete device setup before continuing.
    // This prevents the GPU driver's startup logging from interleaving with
    // init's compositor/editor spawn logging on the serial console.
    loop {
        let _ = sys::wait(&[gpu_ch_handle], u64::MAX);

        if gpu_ch.try_recv(&mut resp_msg) && resp_msg.msg_type == MSG_GPU_READY {
            break;
        }
    }

    // -----------------------------------------------------------------------
    // Allocate shared document buffer (1 page).
    // Core gets read-write (sole writer), editor gets read-only.
    // -----------------------------------------------------------------------
    let mut doc_pa: u64 = 0;
    let _doc_va = sys::dma_alloc(0, &mut doc_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (doc buffer) failed\n");
        sys::exit();
    });

    unsafe { core::ptr::write_bytes(_doc_va as *mut u8, 0, 4096) };

    sys::print(b"     document buffer: 4 KiB shared\n");

    // -----------------------------------------------------------------------
    // Allocate scene graph shared memory (double-buffered).
    // Core writes, compositor reads.
    // -----------------------------------------------------------------------
    let scene_size = scene::TRIPLE_SCENE_SIZE;
    let scene_pages_needed = (scene_size + 4095) / 4096;
    let scene_order = (scene_pages_needed.next_power_of_two().trailing_zeros()) as u32;
    let scene_alloc_bytes = (1usize << scene_order) * 4096;
    let mut scene_pa: u64 = 0;
    let _scene_va = sys::dma_alloc(scene_order, &mut scene_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (scene graph) failed\n");
        sys::exit();
    });

    unsafe { core::ptr::write_bytes(_scene_va as *mut u8, 0, scene_alloc_bytes) };

    sys::print(b"     scene graph: shared memory allocated\n");

    // Unpack font buffer info.
    let (font_pa_val, mono_font_len, prop_font_len, png_offset, png_len) =
        if let Some((pa, mono, prop, png_off, png_l)) = font_buf {
            (pa, mono, prop, png_off, png_l)
        } else {
            (0u64, 0u32, 0u32, 0u32, 0u32)
        };
    let font_total_len = mono_font_len + prop_font_len + png_len;
    let font_pages = if font_total_len > 0 {
        ((font_total_len as u64) + 4095) / 4096
    } else {
        0
    };

    // -----------------------------------------------------------------------
    // Spawn core process.
    // -----------------------------------------------------------------------
    let (core_proc, _core_ch_handle, core_channel_idx) =
        match spawn_with_channel(CORE_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn core\n");
                sys::exit();
            }
        };
    // Share document buffer with core (read-write — sole writer).
    let core_doc_va =
        sys::memory_share(core_proc, doc_pa, DOC_BUF_PAGES, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (core doc) failed\n");
            sys::exit();
        });
    // Share scene graph with core (read-write).
    let scene_page_count = scene_alloc_bytes as u64 / 4096;
    let core_scene_va = sys::memory_share(core_proc, scene_pa, scene_page_count, false)
        .unwrap_or_else(|_| {
            sys::print(b"init: memory_share (core scene) failed\n");
            sys::exit();
        });
    // Share font data with core (read-only, for metrics).
    let core_font_va = if font_pages > 0 {
        sys::memory_share(core_proc, font_pa_val, font_pages, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (core font) failed\n");
            sys::exit();
        }) as u64
    } else {
        0u64
    };
    // Send core config.
    let core_ch = init_channel(core_channel_idx);
    let core_config = CoreConfig {
        doc_va: core_doc_va as u64,
        scene_va: core_scene_va as u64,
        mono_font_va: core_font_va,
        fb_width: logical_w,
        fb_height: logical_h,
        doc_capacity: DOC_BUF_CAPACITY,
        mono_font_len,
        prop_font_len,
        _pad: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_CORE_CONFIG, &core_config) };

    core_ch.send(&msg);

    // Send image config to core (for has_image detection).
    if png_len > 0 {
        let image_va = core_font_va + png_offset as u64;
        let img_config = ImageConfig {
            image_va,
            image_len: png_len,
            _pad: 0,
        };
        let img_msg = unsafe { ipc::Message::from_payload(MSG_IMAGE_CONFIG, &img_config) };

        core_ch.send(&img_msg);
    }

    // Send RTC config to core.
    if rtc_pa != 0 {
        let rtc_config = RtcConfig { mmio_pa: rtc_pa };
        let rtc_msg = unsafe { ipc::Message::from_payload(MSG_RTC_CONFIG, &rtc_config) };

        core_ch.send(&rtc_msg);

        sys::print(b"     rtc config sent to core\n");
    }

    // -----------------------------------------------------------------------
    // Spawn compositor.
    // -----------------------------------------------------------------------
    let (comp_proc, _comp_ch_handle, comp_channel_idx) =
        match spawn_with_channel(COMPOSITOR_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn compositor\n");
                sys::exit();
            }
        };
    // Share framebuffers with compositor (chunk by chunk, scatter-gather).
    let mut comp_fb_va0: usize = 0;
    for i in 0..chunks_per_buf {
        let va = sys::memory_share(comp_proc, pa_table[i], CHUNK_PAGES as u64, false)
            .unwrap_or_else(|_| {
                sys::print(b"init: memory_share (comp fb0) failed\n");
                sys::exit();
            });
        if i == 0 {
            comp_fb_va0 = va;
        }
    }
    let mut comp_fb_va1: usize = 0;
    for i in 0..chunks_per_buf {
        let va = sys::memory_share(
            comp_proc,
            pa_table[chunks_per_buf + i],
            CHUNK_PAGES as u64,
            false,
        )
        .unwrap_or_else(|_| {
            sys::print(b"init: memory_share (comp fb1) failed\n");
            sys::exit();
        });
        if i == 0 {
            comp_fb_va1 = va;
        }
    }
    // Share scene graph with compositor (read-only for rendering).
    let comp_scene_va = sys::memory_share(comp_proc, scene_pa, scene_page_count, false)
        .unwrap_or_else(|_| {
            sys::print(b"init: memory_share (comp scene) failed\n");
            sys::exit();
        });
    // Share font data with compositor (passed to render backend for glyph rasterization).
    let comp_font_va = if font_pages > 0 {
        sys::memory_share(comp_proc, font_pa_val, font_pages, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (comp font) failed\n");
            sys::exit();
        }) as u64
    } else {
        0u64
    };
    // Send compositor config.
    let comp_ch = init_channel(comp_channel_idx);
    let comp_config = CompositorConfig {
        fb_va: comp_fb_va0 as u64,
        fb_va2: comp_fb_va1 as u64,
        scene_va: comp_scene_va as u64,
        mono_font_va: comp_font_va,
        fb_width,
        fb_height,
        mono_font_len,
        prop_font_len,
        scale_factor,
        frame_rate: 60,
        _pad: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_COMPOSITOR_CONFIG, &comp_config) };

    comp_ch.send(&msg);

    // Send image config to compositor (consumed but not used for now).
    if png_len > 0 {
        let image_va = comp_font_va + png_offset as u64;
        let img_config = ImageConfig {
            image_va,
            image_len: png_len,
            _pad: 0,
        };
        let img_msg = unsafe { ipc::Message::from_payload(MSG_IMAGE_CONFIG, &img_config) };

        comp_ch.send(&img_msg);
    }

    // -----------------------------------------------------------------------
    // Create cross-process channels.
    //
    // Core handle layout:
    //   handle 1 = first input (keyboard)
    //   handle 2 = core → compositor (scene update)
    //   handle 3 = core ↔ editor
    //   handle 4+ = additional input devices
    //
    // Compositor handle layout:
    //   handle 1 = core → compositor (scene update)
    //   handle 2 = compositor → GPU (present)
    // -----------------------------------------------------------------------

    // Input → Core channel (keyboard events).
    if !input_devices.is_empty() {
        let (input_proc_handle, input_ch_idx, input_pa, input_irq) = input_devices[0];

        sys::print(b"     creating input\xE2\x86\x92core channel\n");

        let (ic_a, ic_b) = sys::channel_create().unwrap_or_else(|_| {
            sys::print(b"init: channel_create (input-core) failed\n");
            sys::exit();
        });

        *next_channel += 1;

        sys::handle_send(input_proc_handle, ic_a).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-core A) failed\n");
            sys::exit();
        });
        // Send to core (handle 1 in core).
        sys::handle_send(core_proc, ic_b).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-core B) failed\n");
            sys::exit();
        });

        let input_ch = init_channel(input_ch_idx);
        let input_config = DeviceConfig {
            mmio_pa: input_pa,
            irq: input_irq,
            _pad: 0,
        };
        let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &input_config) };

        input_ch.send(&msg);

        sys::print(b"     input device 0 channel created\n");
    }

    // Core → Compositor scene update channel.
    sys::print(b"     creating core\xE2\x86\x92compositor channel\n");

    let (cc_a, cc_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (core-comp) failed\n");
        sys::exit();
    });

    *next_channel += 1;

    // Endpoint A → core (handle 2 = COMPOSITOR_HANDLE in core).
    sys::handle_send(core_proc, cc_a).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-comp A) failed\n");
        sys::exit();
    });
    // Endpoint B → compositor (handle 1 = CORE_HANDLE in compositor).
    sys::handle_send(comp_proc, cc_b).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-comp B) failed\n");
        sys::exit();
    });
    // Compositor → GPU present channel endpoint A → compositor (handle 2).
    sys::handle_send(comp_proc, cg_a).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (comp-gpu A) failed\n");
        sys::exit();
    });

    // -----------------------------------------------------------------------
    // Core ↔ Editor channel.
    // -----------------------------------------------------------------------
    sys::print(b"     spawning text editor\n");

    let (editor_proc, _editor_ch, editor_ch_idx) =
        match spawn_with_channel(TEXT_EDITOR_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn text editor\n");
                sys::exit();
            }
        };
    // Share document buffer with editor (read-only).
    let editor_doc_va =
        sys::memory_share(editor_proc, doc_pa, DOC_BUF_PAGES, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (editor doc) failed\n");
            sys::exit();
        });
    let editor_ch = init_channel(editor_ch_idx);
    let editor_config = EditorConfig {
        doc_va: editor_doc_va as u64,
        doc_capacity: DOC_BUF_CAPACITY,
        _pad: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_EDITOR_CONFIG, &editor_config) };

    editor_ch.send(&msg);

    sys::print(b"     creating core\xE2\x86\x94editor channel\n");

    let (ce_a, ce_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (core-editor) failed\n");
        sys::exit();
    });

    *next_channel += 1;

    // Endpoint A → core (handle 3 = EDITOR_HANDLE in core).
    sys::handle_send(core_proc, ce_a).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-editor A) failed\n");
        sys::exit();
    });
    // Endpoint B → editor (handle 1 in editor's table).
    sys::handle_send(editor_proc, ce_b).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-editor B) failed\n");
        sys::exit();
    });

    // Additional input device channels → core handle 4+.
    for i in 1..input_devices.len() {
        let (input_proc_handle, input_ch_idx, input_pa, input_irq) = input_devices[i];

        sys::print(b"     creating input\xE2\x86\x92core channel\n");

        let (ic_a, ic_b) = sys::channel_create().unwrap_or_else(|_| {
            sys::print(b"init: channel_create (input-core) failed\n");
            sys::exit();
        });

        *next_channel += 1;

        sys::handle_send(input_proc_handle, ic_a).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-core A) failed\n");
            sys::exit();
        });
        sys::handle_send(core_proc, ic_b).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-core B) failed\n");
            sys::exit();
        });

        let input_ch = init_channel(input_ch_idx);
        let input_config = DeviceConfig {
            mmio_pa: input_pa,
            irq: input_irq,
            _pad: 0,
        };
        let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &input_config) };

        input_ch.send(&msg);
    }

    // -----------------------------------------------------------------------
    // Start processes. Order: input drivers, editor, compositor, core.
    // Core starts last because it signals the compositor, and the compositor
    // must be running to receive the signal.
    // -----------------------------------------------------------------------
    for &(input_proc_handle, _, _, _) in input_devices {
        sys::print(b"     starting input driver\n");

        let _ = sys::process_start(input_proc_handle);

        sys::yield_now();
    }

    sys::print(b"     starting text editor\n");

    let _ = sys::process_start(editor_proc);

    sys::yield_now();

    sys::print(b"     starting compositor\n");

    let _ = sys::process_start(comp_proc);

    sys::yield_now();

    sys::print(b"     starting core\n");

    let _ = sys::process_start(core_proc);

    sys::yield_now();

    sys::print(b"     display pipeline running\n");
}
/// Spawn a suspended process, create a channel to it, and send one endpoint.
///
/// Returns (process_handle, init_channel_handle, channel_index) on success.
/// The child receives endpoint B at CHANNEL_SHM_BASE in its address space.
/// Init retains endpoint A at channel_shm_va(channel_index).
fn spawn_with_channel(elf: &[u8], next_channel: &mut usize) -> Option<(u8, u8, usize)> {
    let proc_handle = match sys::process_create(elf.as_ptr(), elf.len()) {
        Ok(h) => h,
        Err(_) => {
            sys::print(b"       spawn: process_create FAILED\n");
            return None;
        }
    };
    let (ch_a, ch_b) = match sys::channel_create() {
        Ok(pair) => pair,
        Err(_) => {
            sys::print(b"       spawn: channel_create FAILED\n");
            return None;
        }
    };

    if let Err(_) = sys::handle_send(proc_handle, ch_b) {
        sys::print(b"       spawn: handle_send FAILED\n");

        return None;
    }

    let channel_idx = *next_channel;

    *next_channel += 1;

    sys::print(b"       spawned (process+channel+handle ok)\n");

    Some((proc_handle, ch_a, channel_idx))
}

#[unsafe(no_mangle)]
pub extern "C" fn _start() -> ! {
    sys::print(b"  \xF0\x9F\x94\xA7 init - proto-os-service starting\n");

    // Kernel channel (channel 0) uses raw bytes — kernel writes directly.
    let kernel_shm = protocol::CHANNEL_SHM_BASE as *const u8;
    let device_count = unsafe { core::ptr::read_volatile(kernel_shm as *const u32) };

    {
        let mut buf = [0u8; 40];
        let prefix = b"     ";

        buf[..prefix.len()].copy_from_slice(prefix);

        let mut pos = prefix.len();

        pos += format_u32(device_count, &mut buf[pos..]);

        let suffix = b" devices in manifest\n";

        buf[pos..pos + suffix.len()].copy_from_slice(suffix);

        pos += suffix.len();

        sys::print(&buf[..pos]);
    }

    // Track channel allocation (0 = kernel, 1+ = ours).
    let mut next_channel: usize = 1;
    // Saved device state for Phase 2 (display pipeline).
    let mut gpu: Option<(u8, u8, usize, u64, u32, bool)> = None; // (proc, ch, ch_idx, pa, irq, virgl)
                                                                 // Multiple input devices (keyboard + tablet). Each entry: (proc, ch_idx, pa, irq).
    let mut input_devices: [(u8, usize, u64, u32); MAX_INPUT_DEVICES] =
        [(0, 0, 0, 0); MAX_INPUT_DEVICES];
    let mut input_count: usize = 0;
    let mut p9: Option<(u8, u8, usize, u64, u32)> = None; // (proc, ch, ch_idx, pa, irq)
    let mut rtc_pa: u64 = 0; // PL031 RTC physical address (0 = not found)
                             // Phase 1: Spawn a driver for each device in the manifest.
    let actual = if device_count > 8 { 8 } else { device_count };

    for i in 0..actual as usize {
        let base = unsafe { kernel_shm.add(8 + i * 16) };
        let dev_pa = unsafe { core::ptr::read_volatile(base as *const u64) };
        let dev_irq = unsafe { core::ptr::read_volatile(base.add(8) as *const u32) };
        let dev_id = unsafe { core::ptr::read_volatile(base.add(12) as *const u32) };

        {
            let mut buf = [0u8; 40];
            let prefix = b"     device ";

            buf[..prefix.len()].copy_from_slice(prefix);

            let mut pos = prefix.len();

            pos += format_u32(i as u32, &mut buf[pos..]);

            let mid = b": id=";

            buf[pos..pos + mid.len()].copy_from_slice(mid);

            pos += mid.len();
            pos += format_u32(dev_id, &mut buf[pos..]);
            buf[pos] = b'\n';
            pos += 1;

            sys::print(&buf[..pos]);
        }

        // PL031 RTC: no driver needed — just save the PA for the compositor.
        if dev_id == DEVICE_PL031_RTC {
            rtc_pa = dev_pa;

            sys::print(b"     pl031 rtc registered\n");

            continue;
        }

        // For GPU devices, probe for virgl support to select the right driver.
        let use_virgl = if dev_id == VIRTIO_DEVICE_GPU {
            probe_virgl(dev_pa)
        } else {
            false
        };

        let elf: &[u8] = match dev_id {
            VIRTIO_DEVICE_BLK => VIRTIO_BLK_ELF,
            VIRTIO_DEVICE_CONSOLE => VIRTIO_CONSOLE_ELF,
            VIRTIO_DEVICE_GPU => {
                if use_virgl {
                    VIRGIL_RENDER_ELF
                } else {
                    VIRTIO_GPU_ELF
                }
            }
            VIRTIO_DEVICE_INPUT => VIRTIO_INPUT_ELF,
            VIRTIO_DEVICE_9P => VIRTIO_9P_ELF,
            _ => {
                let mut buf = [0u8; 48];
                let prefix = b"     skipping unknown device id=";

                buf[..prefix.len()].copy_from_slice(prefix);

                let mut pos = prefix.len();

                pos += format_u32(dev_id, &mut buf[pos..]);
                buf[pos] = b'\n';
                pos += 1;

                sys::print(&buf[..pos]);

                continue;
            }
        };

        {
            let mut buf = [0u8; 48];
            let prefix = b"     spawning driver (elf ";

            buf[..prefix.len()].copy_from_slice(prefix);

            let mut pos = prefix.len();

            pos += format_u32(elf.len() as u32, &mut buf[pos..]);

            let suffix = b" bytes)\n";

            buf[pos..pos + suffix.len()].copy_from_slice(suffix);

            pos += suffix.len();

            sys::print(&buf[..pos]);
        }

        let (proc_h, ch_h, channel_idx) = match spawn_with_channel(elf, &mut next_channel) {
            Some(v) => v,
            None => continue,
        };

        match dev_id {
            VIRTIO_DEVICE_GPU => {
                // Defer GPU startup — needs framebuffer and cross-process channels.
                gpu = Some((proc_h, ch_h, channel_idx, dev_pa, dev_irq, use_virgl));
            }
            VIRTIO_DEVICE_INPUT => {
                // Defer input startup — needs cross-process channel to compositor.
                if input_count < MAX_INPUT_DEVICES {
                    input_devices[input_count] = (proc_h, channel_idx, dev_pa, dev_irq);
                    input_count += 1;
                } else {
                    sys::print(b"     too many input devices, skipping\n");
                }
            }
            VIRTIO_DEVICE_9P => {
                // Defer 9p startup — font read must complete before compositor.
                p9 = Some((proc_h, ch_h, channel_idx, dev_pa, dev_irq));
            }
            _ => {
                // Start simple drivers (blk, console) immediately.
                let ch = init_channel(channel_idx);
                let config = DeviceConfig {
                    mmio_pa: dev_pa,
                    irq: dev_irq,
                    _pad: 0,
                };
                let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &config) };

                ch.send(&msg);

                let _ = sys::process_start(proc_h);
                let name = match dev_id {
                    VIRTIO_DEVICE_BLK => "blk",
                    VIRTIO_DEVICE_CONSOLE => "console",
                    _ => "?",
                };

                sys::print(b"     spawned driver: ");
                sys::print(name.as_bytes());
                sys::print(b"\n");
            }
        }
    }

    // Phase 1.5: Read font files from host via 9p driver (must complete before compositor).
    // Loads monospace + proportional fonts and PNG image.
    // All stored in a single shared buffer: mono | prop | PNG.
    // Tuple: (font_pa, mono_len, prop_len, png_offset, png_len)
    let font_buf: Option<(u64, u32, u32, u32, u32)> =
        if let Some((p9_proc, p9_ch, p9_ch_idx, p9_pa, p9_irq)) = p9 {
            sys::print(b"     loading fonts from host filesystem\n");

            // Allocate font buffer (4 MiB = order 10 = 1024 pages).
            // Holds Recursive variable font (~2.3 MiB) and PNG image.
            let font_order: u32 = 10;
            let font_page_count: u64 = 1u64 << font_order;
            let mut font_pa: u64 = 0;
            let _font_va = sys::dma_alloc(font_order, &mut font_pa).unwrap_or_else(|_| {
                sys::print(b"init: dma_alloc (font buffer) failed\n");
                sys::exit();
            });
            let font_capacity: u32 = (font_page_count as u32) * 4096; // 1 MiB

            unsafe { core::ptr::write_bytes(_font_va as *mut u8, 0, font_capacity as usize) };

            // Share font buffer with 9p driver (read-write).
            let p9_font_va = sys::memory_share(p9_proc, font_pa, font_page_count, false)
                .unwrap_or_else(|_| {
                    sys::print(b"init: memory_share (9p font) failed\n");
                    sys::exit();
                });
            // Send device config via IPC.
            let p9_ch_obj = init_channel(p9_ch_idx);
            let dev_config = DeviceConfig {
                mmio_pa: p9_pa,
                irq: p9_irq,
                _pad: 0,
            };
            let cfg_msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &dev_config) };

            p9_ch_obj.send(&cfg_msg);

            // Start 9p driver.
            sys::print(b"     starting 9p driver\n");

            let _ = sys::process_start(p9_proc);

            // Helper: send a file read request and wait for the response.
            // Returns the number of bytes read, or 0 on failure.
            let read_font_file = |ch_obj: &ipc::Channel,
                                  ch_handle: u8,
                                  target_va: u64,
                                  capacity: u32,
                                  filename: &[u8]|
             -> u32 {
                let mut req_msg = ipc::Message::new(MSG_FS_READ_REQUEST);

                unsafe {
                    let p = req_msg.payload.as_mut_ptr();

                    core::ptr::write_unaligned(p as *mut u64, target_va);
                    core::ptr::write_unaligned(p.add(8) as *mut u32, capacity);
                    core::ptr::write_unaligned(p.add(12) as *mut u32, 0); // _pad

                    // Zero-fill filename area first.
                    core::ptr::write_bytes(p.add(16), 0, 44);
                    core::ptr::copy_nonoverlapping(filename.as_ptr(), p.add(16), filename.len());
                }

                ch_obj.send(&req_msg);

                let _ = sys::channel_signal(ch_handle);
                let mut resp_msg = ipc::Message::new(0);

                loop {
                    let _ = sys::wait(&[ch_handle], u64::MAX);

                    if ch_obj.try_recv(&mut resp_msg) && resp_msg.msg_type == MSG_FS_READ_RESPONSE {
                        break;
                    }
                }

                let (len, status) = unsafe {
                    let p = resp_msg.payload.as_ptr();
                    let len = core::ptr::read_unaligned(p as *const u32);
                    let status = core::ptr::read_unaligned(p.add(4) as *const u32);

                    (len, status)
                };

                if status == 0 && len > 0 {
                    len
                } else {
                    0
                }
            };

            // Load Recursive Variable — one font for both mono and proportional.
            // Content type drives axis values (MONO=1 for code, MONO=0 for prose).
            sys::print(b"     loading recursive-variable.ttf\n");

            let mono_len = read_font_file(
                &p9_ch_obj,
                p9_ch,
                p9_font_va as u64,
                font_capacity,
                b"recursive-variable.ttf",
            );

            if mono_len > 0 {
                let mut buf = [0u8; 48];
                let prefix = b"     mono font loaded: ";

                buf[..prefix.len()].copy_from_slice(prefix);

                let mut pos = prefix.len();

                pos += format_u32(mono_len, &mut buf[pos..]);

                let suffix = b" bytes\n";

                buf[pos..pos + suffix.len()].copy_from_slice(suffix);

                pos += suffix.len();

                sys::print(&buf[..pos]);
            } else {
                sys::print(b"     mono font read failed\n");
            }

            // Recursive Variable serves both mono and proportional via axis values.
            // No separate prop font needed — compositor uses MONO=0 on same data.
            let prop_len: u32 = 0;

            // Load PNG image (test.png) right after the proportional font.
            sys::print(b"     loading test.png\n");

            let png_offset = mono_len + prop_len;
            let png_capacity = font_capacity - png_offset;
            let png_target_va = p9_font_va as u64 + png_offset as u64;
            let png_len =
                read_font_file(&p9_ch_obj, p9_ch, png_target_va, png_capacity, b"test.png");

            if png_len > 0 {
                let mut buf = [0u8; 40];
                let prefix = b"     png loaded: ";

                buf[..prefix.len()].copy_from_slice(prefix);

                let mut pos = prefix.len();

                pos += format_u32(png_len, &mut buf[pos..]);

                let suffix = b" bytes\n";

                buf[pos..pos + suffix.len()].copy_from_slice(suffix);

                pos += suffix.len();

                sys::print(&buf[..pos]);
            } else {
                sys::print(b"     png read failed\n");
            }

            if mono_len > 0 {
                Some((font_pa, mono_len, prop_len, png_offset, png_len))
            } else {
                None
            }
        } else {
            None
        };

    // Phase 2: Display pipeline — select based on virgl probe result.
    if let Some((gpu_proc, gpu_ch_handle, gpu_channel_idx, gpu_pa, gpu_irq, has_virgl)) = gpu {
        if has_virgl {
            setup_virgl_pipeline(
                gpu_proc,
                gpu_ch_handle,
                gpu_channel_idx,
                gpu_pa,
                gpu_irq,
                &input_devices[..input_count],
                font_buf,
                rtc_pa,
                &mut next_channel,
            );
        } else {
            setup_display_pipeline(
                gpu_proc,
                gpu_ch_handle,
                gpu_channel_idx,
                gpu_pa,
                gpu_irq,
                &input_devices[..input_count],
                font_buf,
                rtc_pa,
                &mut next_channel,
            );
        }
    } else {
        sys::print(b"     no gpu found\n");
    }

    // If no GPU device was found, run headless tests.
    if gpu.is_none() {
        sys::print(b"     no gpu found, running headless tests\n");

        // Fuzz test — adversarial syscall testing.
        match sys::process_create(FUZZ_ELF.as_ptr(), FUZZ_ELF.len()) {
            Ok(proc_h) => {
                let _ = sys::process_start(proc_h);
                let _ = sys::wait(&[proc_h], u64::MAX);
            }
            Err(_) => {
                sys::print(b"     fuzz test spawn failed\n");
            }
        }
        // Stress test — IPC/scheduler/timer saturation.
        match sys::process_create(STRESS_ELF.as_ptr(), STRESS_ELF.len()) {
            Ok(proc_h) => {
                let _ = sys::process_start(proc_h);
                let _ = sys::wait(&[proc_h], u64::MAX);
            }
            Err(_) => {
                sys::print(b"     stress test spawn failed\n");
            }
        }
    }

    sys::print(b"  \xF0\x9F\x94\xA7 init - running (idle)\n");

    // Don't exit — child processes are still running their event loops.
    // Idle forever via yield. In the real OS, init would become the OS
    // service process (renderer, metadata DB, input router, compositor).
    loop {
        sys::yield_now();
    }
}
