//! Init — proto-OS-service.
//!
//! The kernel spawns only init. Init reads a device manifest from the kernel
//! via channel shared memory, then spawns and orchestrates all other userspace
//! processes: render services, input drivers, view-engine, document-model,
//! layout-engine, text editor, etc.
//!
//! This is the microkernel pattern: kernel provides mechanism, init provides
//! policy. Matches Fuchsia's component_manager, seL4's root task, QNX's procnto.
//!
//! # Architecture
//!
//! Init decomposes the system into three core processes:
//!
//!   **A — Document Model:** owns document buffer, manages undo, talks to doc service
//!   **B — Layout Engine:** pure function from (doc + viewport) → positioned elements
//!   **C — View Engine:** event loop, input routing, scene graph, animation
//!
//! # Boot phases (named functions)
//!
//! 1. `parse_device_manifest()` — read devices from kernel shared memory
//! 2. `allocate_document_buffer()` — allocate the shared document buffer
//! 3. `load_fonts_native()` / `load_fonts_9p()` — font loading + Content Region
//! 4. `spawn_render_pipeline()` — orchestrates the full pipeline setup:
//!    - `allocate_shared_regions()` — scene graph, pointer/cursor/viewport state, layout results
//!    - `configure_render_service()` — GPU handshake, display query, compositor config
//!    - `spawn_view_engine()` — start C with scene graph, layout results, viewport state
//!    - `spawn_document_model()` — start A with doc buffer, content region
//!    - `spawn_layout_engine()` — start B with doc buffer RO, layout results RW
//!    - `spawn_input_drivers()` — wire input channels to C
//!    - `spawn_editor()` — start editor with doc buffer RO
//!    - `wire_service_channels()` — cross-process IPC (editor↔A, A↔decoder, A↔doc, A↔C, B↔C)
//!    - `start_all_processes()` — start in dependency order
//! 5. `monitor_children()` — post-boot process monitoring loop
//!
//! # Service descriptors
//!
//! After boot, init retains a `ServiceDescriptor` for each spawned process,
//! recording the ELF name, process handle, and config sent. The monitoring
//! loop references them by name for logging. Future restart logic can use them.
//!
//! # IPC topology
//!
//! Init creates three kinds of channels:
//!
//! 1. **Config channels** (init ↔ child) — one per child process. Init sends
//!    configuration as the first ring buffer message before starting the child.
//!
//! 2. **Cross-process channels** — connects services to each other (e.g.
//!    editor↔A, A↔doc service, C↔B, input→C, C→render).
//!
//! 3. **Scene update channel** (C → render service) — signals scene graph
//!    changes. C produces, render service consumes.
//!
//! # Content Region / font loading
//!
//! Font loading and Content Region population currently live in init for
//! bootstrapping. Decision 3 (design journal) designates the document service
//! as the owner of Content Region population. This is deferred to a follow-up
//! when the document service can fully own Content Region lifecycle.
//!
//! # Kernel channel (raw bytes, not ring buffer)
//!
//! The kernel writes the device manifest as raw bytes before starting init.
//! The kernel doesn't use the ipc library — it writes directly to the shared
//! page. This is the only non-ring-buffer channel in the system.
//!
//! ```text
//! offset 0:  device_count (u32)
//! offset 4:  _padding     (u32)
//! offset 8:  device[0]: { pa: u64, irq: u32, device_id: u32 }  (16 bytes)
//! offset 24: device[1]: ...
//! ```

#![no_std]
#![no_main]

extern crate scene;

// ELF binaries for all processes that init can spawn.
// Generated by build.rs and included via env var at compile time.
include!(env!("INIT_EMBEDDED_RS"));

/// Channel shared memory base. The kernel's channel is at page 0.
/// Channels created by init are at subsequent 2-page pairs.
use protocol::compose::{
    CompositorConfig, ImageConfig, RtcConfig, MSG_COMPOSITOR_CONFIG, MSG_IMAGE_CONFIG,
    MSG_RTC_CONFIG,
};
use protocol::layout::{
    CoreLayoutConfig, LayoutEngineConfig, MSG_CORE_LAYOUT_CONFIG, MSG_LAYOUT_ENGINE_CONFIG,
};
use protocol::{
    core_config::{CoreConfig, FrameRateMsg, MSG_CORE_CONFIG, MSG_FRAME_RATE},
    device::{DeviceConfig, MSG_DEVICE_CONFIG},
    editor::{EditorConfig, MSG_EDITOR_CONFIG},
    fs::{MSG_FS_READ_REQUEST, MSG_FS_READ_RESPONSE},
    gpu::{GpuConfig, MSG_DISPLAY_INFO, MSG_GPU_CONFIG, MSG_GPU_READY},
};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// Bytes per pixel (BGRA8888).
const FB_BPP: u32 = 4;
/// Virtio device IDs (must match kernel probe).
const VIRTIO_DEVICE_BLK: u32 = 2;
const VIRTIO_DEVICE_CONSOLE: u32 = 3;
const VIRTIO_DEVICE_GPU: u32 = 16;
const VIRTIO_DEVICE_INPUT: u32 = 18;
const VIRTIO_DEVICE_9P: u32 = 9;
const VIRTIO_DEVICE_METAL: u32 = 22;
/// Virtio MMIO register offsets for feature probing.
const MMIO_DEVICE_FEATURES: usize = 0x010;
const MMIO_DEVICE_FEATURES_SEL: usize = 0x014;
/// Pseudo device ID for the PL031 RTC (matches kernel's DEVICE_ID_PL031_RTC).
const DEVICE_PL031_RTC: u32 = 200;
const PAGE_SIZE: usize = ipc::PAGE_SIZE;
/// Document buffer: 1 page. First 64 bytes = header, rest = content.
const DOC_BUF_PAGES: u64 = 1;
const DOC_BUF_HEADER: u32 = 64;
const DOC_BUF_CAPACITY: u32 = (DOC_BUF_PAGES as u32 * PAGE_SIZE as u32) - DOC_BUF_HEADER;
/// Maximum number of virtio-input devices we can handle (keyboard + tablet).
const MAX_INPUT_DEVICES: usize = 4;
/// Maximum number of services init can track.
const MAX_SERVICES: usize = 16;
/// Boot-phase timeout: 10 seconds in nanoseconds.
const BOOT_TIMEOUT_NS: u64 = 10_000_000_000;
/// Font read timeout: 5 seconds in nanoseconds.
const FONT_READ_TIMEOUT_NS: u64 = 5_000_000_000;

// ---------------------------------------------------------------------------
// Data structures
// ---------------------------------------------------------------------------

/// Records a spawned service for post-boot monitoring and future restart.
///
/// Init retains one descriptor per spawned process. The monitoring loop
/// uses `name` for logging when a child exits. Future restart logic can
/// use the ELF reference and config to re-create a crashed service.
struct ServiceDescriptor {
    /// Human-readable name for logging (e.g. b"view-engine", b"document-model").
    name: &'static [u8],
    /// Kernel process handle.
    process: sys::ProcessHandle,
    /// True if this slot is occupied.
    active: bool,
}

impl ServiceDescriptor {
    const fn empty() -> Self {
        ServiceDescriptor {
            name: b"",
            process: sys::ProcessHandle(0),
            active: false,
        }
    }
}

/// Shared memory allocations for the render pipeline.
///
/// Allocated by `allocate_shared_regions()` before any process is started.
/// Physical addresses are needed for `memory_share()`; virtual addresses
/// are init's own mappings (used for zeroing and header writes).
struct PipelineMemory {
    // Scene graph (triple-buffered).
    scene_pa: u64,
    scene_va: usize,
    scene_page_count: u64,
    // Pointer state register (1 page).
    input_state_pa: u64,
    input_state_va: usize,
    // Layout results (256 KiB). B writes, C reads.
    layout_results_pa: u64,
    layout_results_va: usize,
    layout_results_pages: u64,
    layout_results_size: usize,
    // Viewport state register (1 page). C writes, B reads.
    viewport_state_pa: u64,
    viewport_state_va: usize,
    // Cursor state page (1 page). C writes, render reads.
    cursor_state_pa: u64,
    cursor_state_va: usize,
}

/// Unpacked content region and file store information.
struct ContentInfo {
    content_pa: u64,
    content_size: u32,
    content_pages: u64,
    file_store_pa: u64,
    png_offset: u32,
    png_len: u32,
    file_store_pages: u64,
}

impl ContentInfo {
    fn from_options(
        content_region: Option<(u64, u32)>,
        file_store: Option<(u64, u32, u32)>,
    ) -> Self {
        let (content_pa, content_size) = content_region.unwrap_or((0, 0));
        let content_pages = if content_size > 0 {
            (content_size as u64 + PAGE_SIZE as u64 - 1) / PAGE_SIZE as u64
        } else {
            0
        };
        let (file_store_pa, png_offset, png_len) = file_store.unwrap_or((0, 0, 0));
        let file_store_pages = if png_len > 0 {
            ((png_offset as u64 + png_len as u64) + PAGE_SIZE as u64 - 1) / PAGE_SIZE as u64
        } else {
            0
        };
        ContentInfo {
            content_pa,
            content_size,
            content_pages,
            file_store_pa,
            png_offset,
            png_len,
            file_store_pages,
        }
    }
}

/// Display configuration from render service handshake.
struct DisplayConfig {
    fb_width: u32,
    fb_height: u32,
    logical_w: u32,
    logical_h: u32,
    scale_factor: f32,
    frame_rate: u16,
}

/// Result of parsing the kernel device manifest.
struct DeviceManifest {
    /// GPU device (proc, ch_handle, ch_idx, pa, irq, render_type).
    /// render_type: 0=cpu, 1=virgl, 2=metal.
    gpu: Option<(sys::ProcessHandle, sys::ChannelHandle, usize, u64, u32, u8)>,
    /// Input devices (proc, ch_idx, pa, irq).
    input_devices: [(sys::ProcessHandle, usize, u64, u32); MAX_INPUT_DEVICES],
    input_count: usize,
    /// 9P filesystem driver (proc, ch_handle, ch_idx, pa, irq).
    p9: Option<(sys::ProcessHandle, sys::ChannelHandle, usize, u64, u32)>,
    /// Document service / block device (proc, ch_handle, ch_idx, pa, irq).
    fs_dev: Option<(sys::ProcessHandle, sys::ChannelHandle, usize, u64, u32)>,
    /// PL031 RTC physical address (0 = not found).
    rtc_pa: u64,
}

/// Font loading result from either native or 9P path.
struct FontLoadResult {
    content_region_info: Option<(u64, u32)>,
    file_store_info: Option<(u64, u32, u32)>,
    fs_started: bool,
    doc_core_ch_a: Option<sys::ChannelHandle>,
}

// ---------------------------------------------------------------------------
// Low-level helpers
// ---------------------------------------------------------------------------

fn channel_shm_va(channel_index: usize) -> usize {
    protocol::channel_shm_va(channel_index)
}
/// Create an IPC channel for a given channel index. Init is always endpoint 0.
fn init_channel(channel_index: usize) -> ipc::Channel {
    // SAFETY: channel_shm_va returns the base of a kernel-mapped SHM region at page-aligned boundaries.
    let ch = unsafe { ipc::Channel::from_base(channel_shm_va(channel_index), ipc::PAGE_SIZE, 0) };

    ch.init();

    ch
}
fn print_u32(n: u32) {
    sys::print_u32(n);
}
fn start_process(handle: sys::ProcessHandle, name: &[u8]) {
    if sys::process_start(handle).is_err() {
        sys::print(b"init: process_start failed for ");
        sys::print(name);
        sys::print(b"\n");
    }
}

/// Spawn a suspended process, create a channel to it, and send one endpoint.
///
/// Returns (process_handle, init_channel_handle, channel_index) on success.
/// The child receives endpoint B at CHANNEL_SHM_BASE in its address space.
/// Init retains endpoint A at channel_shm_va(channel_index).
fn spawn_with_channel(
    elf: &[u8],
    next_channel: &mut usize,
) -> Option<(sys::ProcessHandle, sys::ChannelHandle, usize)> {
    let proc_handle = match sys::process_create(elf.as_ptr(), elf.len()) {
        Ok(h) => h,
        Err(_) => {
            sys::print(b"       spawn: process_create FAILED\n");
            return None;
        }
    };
    let (ch_a, ch_b) = match sys::channel_create() {
        Ok(pair) => pair,
        Err(_) => {
            sys::print(b"       spawn: channel_create FAILED\n");
            return None;
        }
    };

    if let Err(_) = sys::handle_send(proc_handle, ch_b.0) {
        sys::print(b"       spawn: handle_send FAILED\n");

        return None;
    }

    let channel_idx = *next_channel;

    *next_channel += 1;

    sys::print(b"       spawned (process+channel+handle ok)\n");

    Some((proc_handle, ch_a, channel_idx))
}

/// Probe a virtio-gpu device for VIRTIO_GPU_F_VIRGL (bit 0) support.
///
/// Maps the device MMIO region, reads the feature register, and checks
/// whether the device advertises 3D virgl capability. This determines
/// whether init spawns virgil-render (GPU-accelerated) or the CPU
/// fallback pipeline (compositor + virtio-gpu 2D).
///
/// # Safety
/// Reads two MMIO registers (DeviceFeaturesSel, DeviceFeatures).
/// Does not change device state — safe to call before driver negotiation.
fn probe_virgl(gpu_pa: u64) -> bool {
    let page_pa = gpu_pa & !(PAGE_SIZE as u64 - 1);
    let page_offset = (gpu_pa & (PAGE_SIZE as u64 - 1)) as usize;

    let va = match sys::device_map(page_pa, PAGE_SIZE as u64) {
        Ok(v) => v,
        Err(_) => {
            sys::print(b"     virgl probe: device_map failed, assuming no virgl\n");
            return false;
        }
    };

    let base = va + page_offset;

    // SAFETY: MMIO register reads. DeviceFeaturesSel at +0x14 selects which
    // 32-bit page of features to read. DeviceFeatures at +0x10 returns the
    // selected page. Writing sel=0 selects bits [31:0]. These are read-only
    // probes that don't alter device state.
    unsafe {
        core::ptr::write_volatile((base + MMIO_DEVICE_FEATURES_SEL) as *mut u32, 0);
    }

    // SAFETY: same MMIO probe as above — reading DeviceFeatures at +0x10.
    let features = unsafe { core::ptr::read_volatile((base + MMIO_DEVICE_FEATURES) as *const u32) };

    // VIRTIO_GPU_F_VIRGL = bit 0
    let has_virgl = features & 1 != 0;

    if has_virgl {
        sys::print(b"     virgl probe: 3D support detected\n");
    } else {
        sys::print(b"     virgl probe: no 3D support, using CPU fallback\n");
    }

    has_virgl
}

// ---------------------------------------------------------------------------
// Phase 1: Parse device manifest
// ---------------------------------------------------------------------------

/// Read the kernel device manifest and spawn a driver process for each device.
///
/// The kernel writes a raw-byte manifest to channel 0 shared memory before
/// starting init. This function parses it, spawns appropriate driver processes
/// (suspended), and categorizes them by type for later pipeline setup.
///
/// Simple drivers (console) are started immediately. Complex drivers (GPU,
/// input, block, 9P) are deferred — they need cross-process channels and
/// shared memory before they can start.
fn parse_device_manifest(next_channel: &mut usize) -> DeviceManifest {
    let kernel_shm = protocol::CHANNEL_SHM_BASE as *const u8;
    // SAFETY: kernel_shm points to kernel channel SHM; volatile ensures visibility of kernel writes.
    let device_count = unsafe { core::ptr::read_volatile(kernel_shm as *const u32) };

    {
        let mut buf = [0u8; 40];
        let prefix = b"     ";

        buf[..prefix.len()].copy_from_slice(prefix);

        let mut pos = prefix.len();

        pos += sys::format_u32(device_count, &mut buf[pos..]);

        let suffix = b" devices in manifest\n";

        buf[pos..pos + suffix.len()].copy_from_slice(suffix);

        pos += suffix.len();

        sys::print(&buf[..pos]);
    }

    let mut manifest = DeviceManifest {
        gpu: None,
        input_devices: [(sys::ProcessHandle(0), 0, 0, 0); MAX_INPUT_DEVICES],
        input_count: 0,
        p9: None,
        fs_dev: None,
        rtc_pa: 0,
    };

    let actual = if device_count > 8 { 8 } else { device_count };

    for i in 0..actual as usize {
        // SAFETY: kernel_shm + 8 + i*16 lies within the kernel channel SHM page (capped at 8 devices);
        // volatile ensures visibility of kernel writes. Each device entry is 16 bytes at 8-byte alignment.
        let base = unsafe { kernel_shm.add(8 + i * 16) };
        let dev_pa = unsafe { core::ptr::read_volatile(base as *const u64) };
        let dev_irq = unsafe { core::ptr::read_volatile(base.add(8) as *const u32) };
        let dev_id = unsafe { core::ptr::read_volatile(base.add(12) as *const u32) };

        {
            let mut buf = [0u8; 40];
            let prefix = b"     device ";

            buf[..prefix.len()].copy_from_slice(prefix);

            let mut pos = prefix.len();

            pos += sys::format_u32(i as u32, &mut buf[pos..]);

            let mid = b": id=";

            buf[pos..pos + mid.len()].copy_from_slice(mid);

            pos += mid.len();
            pos += sys::format_u32(dev_id, &mut buf[pos..]);
            buf[pos] = b'\n';
            pos += 1;

            sys::print(&buf[..pos]);
        }

        // PL031 RTC: no driver needed — just save the PA for the compositor.
        if dev_id == DEVICE_PL031_RTC {
            manifest.rtc_pa = dev_pa;

            sys::print(b"     pl031 rtc registered\n");

            continue;
        }

        // For GPU devices, probe for virgl support to select the right driver.
        let use_virgl = if dev_id == VIRTIO_DEVICE_GPU {
            probe_virgl(dev_pa)
        } else {
            false
        };

        let elf: &[u8] = match dev_id {
            VIRTIO_DEVICE_BLK => DOCUMENT_ELF,
            VIRTIO_DEVICE_CONSOLE => VIRTIO_CONSOLE_ELF,
            VIRTIO_DEVICE_GPU => {
                if use_virgl {
                    VIRGIL_RENDER_ELF
                } else {
                    CPU_RENDER_ELF
                }
            }
            VIRTIO_DEVICE_METAL => METAL_RENDER_ELF,
            VIRTIO_DEVICE_INPUT => VIRTIO_INPUT_ELF,
            VIRTIO_DEVICE_9P => VIRTIO_9P_ELF,
            _ => {
                let mut buf = [0u8; 48];
                let prefix = b"     skipping unknown device id=";

                buf[..prefix.len()].copy_from_slice(prefix);

                let mut pos = prefix.len();

                pos += sys::format_u32(dev_id, &mut buf[pos..]);
                buf[pos] = b'\n';
                pos += 1;

                sys::print(&buf[..pos]);

                continue;
            }
        };

        {
            let mut buf = [0u8; 48];
            let prefix = b"     spawning driver (elf ";

            buf[..prefix.len()].copy_from_slice(prefix);

            let mut pos = prefix.len();

            pos += sys::format_u32(elf.len() as u32, &mut buf[pos..]);

            let suffix = b" bytes)\n";

            buf[pos..pos + suffix.len()].copy_from_slice(suffix);

            pos += suffix.len();

            sys::print(&buf[..pos]);
        }

        let (proc_h, ch_h, channel_idx) = match spawn_with_channel(elf, next_channel) {
            Some(v) => v,
            None => continue,
        };

        match dev_id {
            VIRTIO_DEVICE_GPU => {
                let rtype: u8 = if use_virgl { 1 } else { 0 };
                manifest.gpu = Some((proc_h, ch_h, channel_idx, dev_pa, dev_irq, rtype));
            }
            VIRTIO_DEVICE_METAL => {
                manifest.gpu = Some((proc_h, ch_h, channel_idx, dev_pa, dev_irq, 2));
            }
            VIRTIO_DEVICE_INPUT => {
                if manifest.input_count < MAX_INPUT_DEVICES {
                    manifest.input_devices[manifest.input_count] =
                        (proc_h, channel_idx, dev_pa, dev_irq);
                    manifest.input_count += 1;
                } else {
                    sys::print(b"     too many input devices, skipping\n");
                }
            }
            VIRTIO_DEVICE_9P => {
                manifest.p9 = Some((proc_h, ch_h, channel_idx, dev_pa, dev_irq));
            }
            VIRTIO_DEVICE_BLK => {
                manifest.fs_dev = Some((proc_h, ch_h, channel_idx, dev_pa, dev_irq));
            }
            _ => {
                // Start simple drivers (console) immediately.
                let ch = init_channel(channel_idx);
                let config = DeviceConfig {
                    mmio_pa: dev_pa,
                    irq: dev_irq,
                    init_handle: 0,
                    service_handle: 0xFF,
                    _pad: [0; 2],
                };
                // SAFETY: DeviceConfig fits within 60-byte payload; msg_type matches the payload type.
                let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &config) };

                ch.send(&msg);

                start_process(proc_h, b"driver");

                sys::print(b"     spawned driver: console\n");
            }
        }
    }

    manifest
}

// ---------------------------------------------------------------------------
// Phase 1.5: Font loading (Content Region + File Store)
// ---------------------------------------------------------------------------

/// Allocate the shared document buffer (1 page = 4 KiB).
///
/// Returns (physical_address, virtual_address).
fn allocate_document_buffer() -> (u64, usize) {
    let mut doc_pa: u64 = 0;
    let doc_va = sys::dma_alloc(0, &mut doc_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (doc buffer) failed\n");
        sys::exit();
    });
    // SAFETY: doc_va is a 1-page DMA region just allocated; zeroing PAGE_SIZE bytes is within bounds.
    unsafe { core::ptr::write_bytes(doc_va as *mut u8, 0, PAGE_SIZE) };
    (doc_pa, doc_va)
}

/// Load fonts from the native document service (block device).
///
/// Allocates Content Region (4 MiB) and File Store (1 MiB), shares them
/// with the document service, starts the service, queries fonts by name,
/// and loads them into the Content Region. Also loads test.png into the
/// File Store for the PNG decoder.
fn load_fonts_native(
    fs_proc: sys::ProcessHandle,
    fs_ch: sys::ChannelHandle,
    fs_ch_idx: usize,
    fs_pa: u64,
    fs_irq: u32,
    doc_pa: u64,
    next_channel: &mut usize,
) -> FontLoadResult {
    sys::print(b"     loading fonts from native filesystem\n");

    // Allocate Content Region (4 MiB = order 10 = 1024 pages).
    let content_order: u32 = 10;
    let content_page_count: u64 = 1u64 << content_order;
    let mut content_pa: u64 = 0;
    let content_va = sys::dma_alloc(content_order, &mut content_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (content region) failed\n");
        sys::exit();
    });
    let content_capacity: u32 = (content_page_count as u32) * PAGE_SIZE as u32; // 4 MiB

    // SAFETY: content_va..+content_capacity is the DMA region just allocated; zeroing is within bounds.
    unsafe { core::ptr::write_bytes(content_va as *mut u8, 0, content_capacity as usize) };

    // Allocate File Store (1 MiB = order 8 = 256 pages).
    let fs_order: u32 = 8;
    let fs_page_count: u64 = 1u64 << fs_order;
    let mut store_pa: u64 = 0;
    let _store_va = sys::dma_alloc(fs_order, &mut store_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (file store) failed\n");
        sys::exit();
    });
    let fs_capacity: u32 = (fs_page_count as u32) * PAGE_SIZE as u32; // 1 MiB

    // SAFETY: store_va..+fs_capacity is the DMA region just allocated; zeroing is within bounds.
    unsafe { core::ptr::write_bytes(_store_va as *mut u8, 0, fs_capacity as usize) };

    // Share Content Region with document service (read-write, for writing font data).
    let doc_content_va = sys::memory_share(fs_proc, content_pa, content_page_count, false)
        .unwrap_or_else(|_| {
            sys::print(b"init: memory_share (doc content) failed\n");
            sys::exit();
        });

    // Share File Store with document service (read-write, for writing PNG data).
    let doc_fs_va =
        sys::memory_share(fs_proc, store_pa, fs_page_count, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (doc file store) failed\n");
            sys::exit();
        });

    // Share document buffer with document service (read-write).
    let fs_doc_va =
        sys::memory_share(fs_proc, doc_pa, DOC_BUF_PAGES, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (doc buf) failed\n");
            sys::exit();
        });

    // Pre-create A ↔ document service channel. Endpoint B is sent to
    // the document service BEFORE it starts (handle_send requires unstarted
    // processes). Endpoint A is saved and sent to A later.
    let (doc_core_a, doc_core_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (core-doc early) failed\n");
        sys::exit();
    });
    *next_channel += 1;

    sys::handle_send(fs_proc, doc_core_b.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (doc core-ch B) failed\n");
        sys::exit();
    });

    // Send config to document service via init channel.
    let fs_ch_obj = init_channel(fs_ch_idx);
    let doc_config = protocol::document::DocConfig {
        mmio_pa: fs_pa,
        irq: fs_irq,
        _pad: 0,
        doc_va: fs_doc_va as u64,
        doc_capacity: DOC_BUF_CAPACITY,
        _pad2: 0,
        content_va: doc_content_va as u64,
        content_size: content_capacity,
        init_handle: 0,
        core_handle: 1,
        _pad3: [0; 2],
    };
    let doc_msg =
        unsafe { ipc::Message::from_payload(protocol::document::MSG_DOC_CONFIG, &doc_config) };
    fs_ch_obj.send(&doc_msg);

    // Start document service.
    sys::print(b"     starting document service\n");
    start_process(fs_proc, b"document");
    sys::yield_now();

    // Wait for MSG_DOC_READY.
    sys::print(b"     waiting for document service ready\n");
    let mut ready = false;
    {
        let mut retries = 0u32;
        let mut msg = ipc::Message::new(0);

        loop {
            match sys::wait(&[fs_ch.0], BOOT_TIMEOUT_NS) {
                Ok(_) => {
                    while fs_ch_obj.try_recv(&mut msg) {
                        if msg.msg_type == protocol::document::MSG_DOC_READY {
                            ready = true;
                            break;
                        }
                    }
                    if ready {
                        break;
                    }
                }
                Err(sys::SyscallError::WouldBlock) => {
                    retries += 1;
                    sys::print(b"init: timeout waiting for doc ready (retry)\n");
                    if retries >= 3 {
                        sys::print(b"init: document service not ready, fallback\n");
                        break;
                    }
                }
                _ => break,
            }
        }
    }

    if !ready {
        sys::print(b"init: document service failed to start\n");
        return FontLoadResult {
            content_region_info: None,
            file_store_info: None,
            fs_started: false,
            doc_core_ch_a: None,
        };
    }

    sys::print(b"     document service ready\n");

    // ── Query and load fonts from the native store ───────────

    // Helper: send a query and wait for the result.
    let query_attr =
        |ch_obj: &ipc::Channel, ch_handle: sys::ChannelHandle, key: &[u8], value: &[u8]| -> u64 {
            let mut q = protocol::document::DocQuery {
                query_type: 2, // attribute query
                data_len: 0,
                data: [0u8; 48],
            };
            let total_len = key.len() + 1 + value.len();
            assert!(total_len <= 48, "query data too long");
            q.data[..key.len()].copy_from_slice(key);
            q.data[key.len()] = 0;
            q.data[key.len() + 1..key.len() + 1 + value.len()].copy_from_slice(value);
            q.data_len = total_len as u32;

            let msg =
                unsafe { ipc::Message::from_payload(protocol::document::MSG_DOC_QUERY, &q) };
            ch_obj.send(&msg);
            let _ = sys::channel_signal(ch_handle);

            let mut resp = ipc::Message::new(0);
            let mut retries = 0u32;

            loop {
                match sys::wait(&[ch_handle.0], FONT_READ_TIMEOUT_NS) {
                    Ok(_) => {
                        if ch_obj.try_recv(&mut resp)
                            && resp.msg_type == protocol::document::MSG_DOC_QUERY_RESULT
                        {
                            if let Some(protocol::document::Message::DocQueryResult(result)) =
                                protocol::document::decode(resp.msg_type, &resp.payload)
                            {
                                if result.count > 0 {
                                    return result.file_ids[0];
                                }
                            }
                            return 0;
                        }
                    }
                    Err(sys::SyscallError::WouldBlock) => {
                        retries += 1;
                        if retries >= 3 {
                            return 0;
                        }
                    }
                    _ => return 0,
                }
            }
        };

    // Helper: send a read request and wait for the response.
    let doc_read = |ch_obj: &ipc::Channel,
                    ch_handle: sys::ChannelHandle,
                    file_id: u64,
                    target_va: u64,
                    capacity: u32|
     -> u32 {
        let r = protocol::document::DocRead {
            file_id,
            target_va,
            capacity,
            _pad: 0,
        };
        let msg = unsafe { ipc::Message::from_payload(protocol::document::MSG_DOC_READ, &r) };
        ch_obj.send(&msg);
        let _ = sys::channel_signal(ch_handle);

        let mut resp = ipc::Message::new(0);
        let mut retries = 0u32;

        loop {
            match sys::wait(&[ch_handle.0], FONT_READ_TIMEOUT_NS) {
                Ok(_) => {
                    if ch_obj.try_recv(&mut resp)
                        && resp.msg_type == protocol::document::MSG_DOC_READ_DONE
                    {
                        if let Some(protocol::document::Message::DocReadDone(done)) =
                            protocol::document::decode(resp.msg_type, &resp.payload)
                        {
                            if done.status == 0 {
                                return done.len;
                            }
                        }
                        return 0;
                    }
                }
                Err(sys::SyscallError::WouldBlock) => {
                    retries += 1;
                    if retries >= 3 {
                        return 0;
                    }
                }
                _ => return 0,
            }
        }
    };

    let data_start = protocol::content::CONTENT_HEADER_SIZE as u32;
    let mut data_cursor = data_start;
    let mut entry_count: u32 = 0;

    // Font loading table: (attribute name, content_id, log label).
    let fonts: [(&[u8], u32, &[u8]); 6] = [
        (
            b"JetBrains Mono",
            protocol::content::CONTENT_ID_FONT_MONO,
            b"mono",
        ),
        (b"Inter", protocol::content::CONTENT_ID_FONT_SANS, b"sans"),
        (
            b"Source Serif 4",
            protocol::content::CONTENT_ID_FONT_SERIF,
            b"serif",
        ),
        (
            b"JetBrains Mono Italic",
            protocol::content::CONTENT_ID_FONT_MONO_ITALIC,
            b"mono-italic",
        ),
        (
            b"Inter Italic",
            protocol::content::CONTENT_ID_FONT_SANS_ITALIC,
            b"sans-italic",
        ),
        (
            b"Source Serif 4 Italic",
            protocol::content::CONTENT_ID_FONT_SERIF_ITALIC,
            b"serif-italic",
        ),
    ];

    let mut mono_ok = false;

    for (font_name, content_id, label) in &fonts {
        sys::print(b"     loading font: ");
        sys::print(label);
        sys::print(b"\n");

        let file_id = query_attr(&fs_ch_obj, fs_ch, b"name", font_name);
        if file_id == 0 {
            sys::print(b"     font not found: ");
            sys::print(label);
            sys::print(b"\n");
            continue;
        }

        let target_va = doc_content_va as u64 + data_cursor as u64;
        let capacity = content_capacity - data_cursor;
        let len = doc_read(&fs_ch_obj, fs_ch, file_id, target_va, capacity);

        if len > 0 {
            sys::print(b"     ");
            sys::print(label);
            sys::print(b" font loaded: ");
            let mut buf = [0u8; 16];
            let n = sys::format_u32(len, &mut buf);
            sys::print(&buf[..n]);
            sys::print(b" bytes\n");

            // SAFETY: content_va is a valid DMA allocation; header fits within
            // CONTENT_HEADER_SIZE.
            let header =
                unsafe { &mut *(content_va as *mut protocol::content::ContentRegionHeader) };
            header.entries[entry_count as usize] = protocol::content::ContentEntry {
                content_id: *content_id,
                offset: data_cursor,
                length: len,
                class: protocol::content::ContentClass::Font as u8,
                _pad: [0; 3],
                width: 0,
                height: 0,
                generation: 0,
            };
            entry_count += 1;
            data_cursor += len;

            if *content_id == protocol::content::CONTENT_ID_FONT_MONO {
                mono_ok = true;
            }
        } else {
            sys::print(b"     ");
            sys::print(label);
            sys::print(b" font read failed\n");
        }
    }

    // Write Content Region header.
    // SAFETY: content_va is a valid DMA allocation; header struct fits within
    // CONTENT_HEADER_SIZE.
    let header = unsafe { &mut *(content_va as *mut protocol::content::ContentRegionHeader) };
    header.magic = protocol::content::CONTENT_REGION_MAGIC;
    header.version = protocol::content::CONTENT_REGION_VERSION;
    header.entry_count = entry_count;
    header.max_entries = protocol::content::MAX_CONTENT_ENTRIES as u32;
    header.data_offset = data_start;
    header.next_alloc = data_cursor;

    sys::print(b"     content region header written\n");

    // Load test.png into File Store via document service.
    sys::print(b"     loading test.png\n");
    let png_file_id = query_attr(&fs_ch_obj, fs_ch, b"name", b"test");
    let png_len = if png_file_id != 0 {
        doc_read(&fs_ch_obj, fs_ch, png_file_id, doc_fs_va as u64, fs_capacity)
    } else {
        0
    };

    if png_len > 0 {
        let mut buf = [0u8; 40];
        let prefix = b"     png loaded: ";
        buf[..prefix.len()].copy_from_slice(prefix);
        let mut pos = prefix.len();
        pos += sys::format_u32(png_len, &mut buf[pos..]);
        let suffix = b" bytes\n";
        buf[pos..pos + suffix.len()].copy_from_slice(suffix);
        pos += suffix.len();
        sys::print(&buf[..pos]);
    } else {
        sys::print(b"     png read failed\n");
    }

    // Signal end of boot-query phase.
    let boot_done_msg = ipc::Message::new(protocol::document::MSG_DOC_BOOT_DONE);
    fs_ch_obj.send(&boot_done_msg);
    let _ = sys::channel_signal(fs_ch);

    FontLoadResult {
        content_region_info: if mono_ok {
            Some((content_pa, content_capacity))
        } else {
            None
        },
        file_store_info: if png_len > 0 {
            Some((store_pa, 0u32, png_len))
        } else {
            None
        },
        fs_started: true,
        doc_core_ch_a: Some(doc_core_a),
    }
}

/// Load fonts from the host filesystem via the 9P driver (fallback path).
///
/// Same allocation pattern as `load_fonts_native()` but reads files by
/// filename from the 9P share instead of querying the document service.
fn load_fonts_9p(
    p9_proc: sys::ProcessHandle,
    p9_ch: sys::ChannelHandle,
    p9_ch_idx: usize,
    p9_pa: u64,
    p9_irq: u32,
) -> FontLoadResult {
    sys::print(b"     loading fonts from host filesystem (9p fallback)\n");

    // Allocate Content Region (4 MiB = order 10 = 1024 pages).
    let content_order: u32 = 10;
    let content_page_count: u64 = 1u64 << content_order;
    let mut content_pa: u64 = 0;
    let content_va = sys::dma_alloc(content_order, &mut content_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (content region) failed\n");
        sys::exit();
    });
    let content_capacity: u32 = (content_page_count as u32) * PAGE_SIZE as u32;

    // SAFETY: content_va..+content_capacity is the DMA region just allocated; zeroing is within bounds.
    unsafe { core::ptr::write_bytes(content_va as *mut u8, 0, content_capacity as usize) };

    // Allocate File Store (1 MiB = order 8 = 256 pages).
    let fs_order: u32 = 8;
    let fs_page_count: u64 = 1u64 << fs_order;
    let mut store_pa: u64 = 0;
    let _store_va = sys::dma_alloc(fs_order, &mut store_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (file store) failed\n");
        sys::exit();
    });
    let fs_capacity: u32 = (fs_page_count as u32) * PAGE_SIZE as u32;

    // SAFETY: store_va..+fs_capacity is the DMA region just allocated; zeroing is within bounds.
    unsafe { core::ptr::write_bytes(_store_va as *mut u8, 0, fs_capacity as usize) };

    // Share Content Region with 9p driver (read-write, for writing font data).
    let p9_content_va = sys::memory_share(p9_proc, content_pa, content_page_count, false)
        .unwrap_or_else(|_| {
            sys::print(b"init: memory_share (9p content) failed\n");
            sys::exit();
        });

    // Share File Store with 9p driver (read-write, for writing PNG data).
    let p9_fs_va =
        sys::memory_share(p9_proc, store_pa, fs_page_count, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (9p file store) failed\n");
            sys::exit();
        });

    // Send device config via IPC.
    let p9_ch_obj = init_channel(p9_ch_idx);
    let dev_config = DeviceConfig {
        mmio_pa: p9_pa,
        irq: p9_irq,
        init_handle: 0,
        service_handle: 0xFF,
        _pad: [0; 2],
    };
    // SAFETY: same as DeviceConfig from_payload above.
    let cfg_msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &dev_config) };
    p9_ch_obj.send(&cfg_msg);

    // Start 9p driver.
    sys::print(b"     starting 9p driver\n");
    start_process(p9_proc, b"9p");

    // Helper: send a file read request and wait for the response.
    let read_file = |ch_obj: &ipc::Channel,
                     ch_handle: sys::ChannelHandle,
                     target_va: u64,
                     capacity: u32,
                     filename: &[u8]|
     -> u32 {
        let mut req_msg = ipc::Message::new(MSG_FS_READ_REQUEST);

        // SAFETY: payload is 60 bytes; writes at offsets 0..8 (u64), 8..12 (u32), 12..16 (u32),
        // 16..60 (filename) stay within bounds. Unaligned writes used because payload is [u8].
        unsafe {
            let p = req_msg.payload.as_mut_ptr();
            core::ptr::write_unaligned(p as *mut u64, target_va);
            core::ptr::write_unaligned(p.add(8) as *mut u32, capacity);
            core::ptr::write_unaligned(p.add(12) as *mut u32, 0);
            core::ptr::write_bytes(p.add(16), 0, 44);
            assert!(filename.len() <= 44, "filename too long for IPC payload");
            core::ptr::copy_nonoverlapping(filename.as_ptr(), p.add(16), filename.len());
        }

        ch_obj.send(&req_msg);
        let _ = sys::channel_signal(ch_handle);
        let mut resp_msg = ipc::Message::new(0);
        let mut got_response = false;
        let mut retries = 0u32;

        loop {
            match sys::wait(&[ch_handle.0], FONT_READ_TIMEOUT_NS) {
                Ok(_) => {
                    if ch_obj.try_recv(&mut resp_msg)
                        && resp_msg.msg_type == MSG_FS_READ_RESPONSE
                    {
                        got_response = true;
                        break;
                    }
                }
                Err(sys::SyscallError::WouldBlock) => {
                    retries += 1;
                    sys::print(b"init: timeout waiting for font read (retry)\n");
                    if retries >= 3 {
                        break;
                    }
                }
                _ => break,
            }
        }

        if !got_response {
            return 0;
        }

        // SAFETY: payload is 60 bytes; reads at offsets 0..4 and 4..8 are in bounds.
        let (len, status) = unsafe {
            let p = resp_msg.payload.as_ptr();
            (
                core::ptr::read_unaligned(p as *const u32),
                core::ptr::read_unaligned(p.add(4) as *const u32),
            )
        };

        if status == 0 && len > 0 {
            len
        } else {
            0
        }
    };

    let data_start = protocol::content::CONTENT_HEADER_SIZE as u32;
    let mut data_cursor = data_start;
    let mut entry_count: u32 = 0;

    // Load 6 fonts via 9p (regular + italic for each family).
    let fonts_9p: [(&[u8], u32, &[u8]); 6] = [
        (
            b"jetbrains-mono.ttf",
            protocol::content::CONTENT_ID_FONT_MONO,
            b"mono",
        ),
        (
            b"inter.ttf",
            protocol::content::CONTENT_ID_FONT_SANS,
            b"sans",
        ),
        (
            b"source-serif-4.ttf",
            protocol::content::CONTENT_ID_FONT_SERIF,
            b"serif",
        ),
        (
            b"jetbrains-mono-italic.ttf",
            protocol::content::CONTENT_ID_FONT_MONO_ITALIC,
            b"mono-italic",
        ),
        (
            b"inter-italic.ttf",
            protocol::content::CONTENT_ID_FONT_SANS_ITALIC,
            b"sans-italic",
        ),
        (
            b"source-serif-4-italic.ttf",
            protocol::content::CONTENT_ID_FONT_SERIF_ITALIC,
            b"serif-italic",
        ),
    ];

    let mut mono_len_9p: u32 = 0;

    for (filename, content_id, label) in &fonts_9p {
        sys::print(b"     loading ");
        sys::print(filename);
        sys::print(b"\n");

        let target_va = p9_content_va as u64 + data_cursor as u64;
        let capacity = content_capacity - data_cursor;
        let len = read_file(&p9_ch_obj, p9_ch, target_va, capacity, filename);

        if len > 0 {
            sys::print(b"     ");
            sys::print(label);
            sys::print(b" font loaded: ");
            let mut buf = [0u8; 16];
            let n = sys::format_u32(len, &mut buf);
            sys::print(&buf[..n]);
            sys::print(b" bytes\n");

            // SAFETY: content_va is a valid DMA allocation; header fits within CONTENT_HEADER_SIZE.
            let header =
                unsafe { &mut *(content_va as *mut protocol::content::ContentRegionHeader) };
            header.entries[entry_count as usize] = protocol::content::ContentEntry {
                content_id: *content_id,
                offset: data_cursor,
                length: len,
                class: protocol::content::ContentClass::Font as u8,
                _pad: [0; 3],
                width: 0,
                height: 0,
                generation: 0,
            };
            entry_count += 1;
            data_cursor += len;

            if *content_id == protocol::content::CONTENT_ID_FONT_MONO {
                mono_len_9p = len;
            }
        } else {
            sys::print(b"     ");
            sys::print(label);
            sys::print(b" font read failed\n");
        }
    }

    // Write Content Region header.
    let header = unsafe { &mut *(content_va as *mut protocol::content::ContentRegionHeader) };
    header.magic = protocol::content::CONTENT_REGION_MAGIC;
    header.version = protocol::content::CONTENT_REGION_VERSION;
    header.entry_count = entry_count;
    header.max_entries = protocol::content::MAX_CONTENT_ENTRIES as u32;
    header.data_offset = data_start;
    header.next_alloc = data_cursor;

    sys::print(b"     content region header written\n");

    // Load PNG into File Store.
    sys::print(b"     loading test.png\n");
    let png_len = read_file(&p9_ch_obj, p9_ch, p9_fs_va as u64, fs_capacity, b"test.png");

    if png_len > 0 {
        let mut buf = [0u8; 40];
        let prefix = b"     png loaded: ";
        buf[..prefix.len()].copy_from_slice(prefix);
        let mut pos = prefix.len();
        pos += sys::format_u32(png_len, &mut buf[pos..]);
        let suffix = b" bytes\n";
        buf[pos..pos + suffix.len()].copy_from_slice(suffix);
        pos += suffix.len();
        sys::print(&buf[..pos]);
    } else {
        sys::print(b"     png read failed\n");
    }

    FontLoadResult {
        content_region_info: if mono_len_9p > 0 {
            Some((content_pa, content_capacity))
        } else {
            None
        },
        file_store_info: if png_len > 0 {
            Some((store_pa, 0u32, png_len))
        } else {
            None
        },
        fs_started: false,
        doc_core_ch_a: None,
    }
}

// ---------------------------------------------------------------------------
// Phase 2: Render pipeline setup (sub-functions)
// ---------------------------------------------------------------------------

/// Allocate all shared memory regions needed for the render pipeline.
///
/// This must happen before any process is started because `memory_share`
/// requires the target process to be unstarted. Allocates: scene graph,
/// pointer state, layout results, viewport state, and cursor state.
fn allocate_shared_regions() -> PipelineMemory {
    // Scene graph (triple-buffered).
    let scene_size = scene::TRIPLE_SCENE_SIZE;
    let scene_pages_needed = (scene_size + ipc::PAGE_SIZE - 1) / ipc::PAGE_SIZE;
    let scene_order = (scene_pages_needed.next_power_of_two().trailing_zeros()) as u32;
    let scene_alloc_bytes = (1usize << scene_order) * ipc::PAGE_SIZE;
    let mut scene_pa: u64 = 0;
    let scene_va = sys::dma_alloc(scene_order, &mut scene_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (scene graph) failed\n");
        sys::exit();
    });

    // SAFETY: scene_va..scene_va+scene_alloc_bytes is the DMA region just allocated above; zeroing is valid.
    unsafe { core::ptr::write_bytes(scene_va as *mut u8, 0, scene_alloc_bytes) };

    sys::print(b"     scene graph: shared memory allocated\n");

    let scene_page_count = scene_alloc_bytes as u64 / PAGE_SIZE as u64;

    // Pointer state register (1 page). Shared with input drivers (write),
    // core (read-only), and render service (read-only for cursor plane).
    let mut input_state_pa: u64 = 0;
    let input_state_va = sys::dma_alloc(0, &mut input_state_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (input state) failed\n");
        sys::exit();
    });

    // SAFETY: input_state_va is a valid 1-page DMA region; zeroing PAGE_SIZE bytes is within bounds.
    unsafe { core::ptr::write_bytes(input_state_va as *mut u8, 0, PAGE_SIZE) };

    sys::print(b"     pointer state register: 4 KiB shared\n");

    // Layout results region (256 KiB = 16 pages = order 4).
    // Shared with layout-engine (read-write) and core (read-only).
    let layout_results_order: u32 = 4; // 2^4 = 16 pages = 256 KiB
    let layout_results_pages: u64 = 1u64 << layout_results_order;
    let layout_results_size: usize = (layout_results_pages as usize) * PAGE_SIZE;
    let mut layout_results_pa: u64 = 0;
    let layout_results_va =
        sys::dma_alloc(layout_results_order, &mut layout_results_pa).unwrap_or_else(|_| {
            sys::print(b"init: dma_alloc (layout results) failed\n");
            sys::exit();
        });
    // SAFETY: layout_results_va is a valid DMA region; zeroing is within bounds.
    unsafe { core::ptr::write_bytes(layout_results_va as *mut u8, 0, layout_results_size) };
    sys::print(b"     layout results: 256 KiB shared\n");

    // Viewport state register (1 page). C writes viewport params, B reads.
    let mut viewport_state_pa: u64 = 0;
    let viewport_state_va = sys::dma_alloc(0, &mut viewport_state_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (viewport state) failed\n");
        sys::exit();
    });
    // SAFETY: viewport_state_va is a valid 1-page DMA region.
    unsafe { core::ptr::write_bytes(viewport_state_va as *mut u8, 0, PAGE_SIZE) };
    sys::print(b"     viewport state register: 4 KiB shared\n");

    // Cursor state page (1 page). Shared with core (read-write) and
    // render service (read-only). Core writes cursor shape path data +
    // metadata; render service GPU-rasterizes and applies to cursor plane.
    let mut cursor_state_pa: u64 = 0;
    let cursor_state_va = sys::dma_alloc(0, &mut cursor_state_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (cursor state) failed\n");
        sys::exit();
    });

    // SAFETY: cursor_state_va is a valid 1-page DMA region; zeroing PAGE_SIZE bytes is within bounds.
    unsafe { core::ptr::write_bytes(cursor_state_va as *mut u8, 0, PAGE_SIZE) };

    sys::print(b"     cursor state page: 4 KiB shared\n");

    PipelineMemory {
        scene_pa,
        scene_va,
        scene_page_count,
        input_state_pa,
        input_state_va,
        layout_results_pa,
        layout_results_va,
        layout_results_pages,
        layout_results_size,
        viewport_state_pa,
        viewport_state_va,
        cursor_state_pa,
        cursor_state_va,
    }
}

/// Configure the render service: share memory, start it, perform display
/// handshake, send GPU config and compositor config.
///
/// Returns (DisplayConfig, scene_update_channel_endpoint_A).
fn configure_render_service(
    name: &[u8],
    gpu_proc: sys::ProcessHandle,
    gpu_ch_handle: sys::ChannelHandle,
    gpu_channel_idx: usize,
    gpu_pa: u64,
    gpu_irq: u32,
    mem: &PipelineMemory,
    content: &ContentInfo,
    next_channel: &mut usize,
) -> (DisplayConfig, sys::ChannelHandle) {
    // Create core→render service scene update channel.
    sys::print(b"     creating core\xE2\x86\x92");
    sys::print(name);
    sys::print(b" channel\n");

    let (cv_a, cv_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (core-render) failed\n");
        sys::exit();
    });

    *next_channel += 1;

    // Share memory with render service BEFORE starting it.
    let render_scene_va = sys::memory_share(gpu_proc, mem.scene_pa, mem.scene_page_count, false)
        .unwrap_or_else(|_| {
            sys::print(b"init: memory_share (render scene) failed\n");
            sys::exit();
        });

    let render_content_va = if content.content_pages > 0 {
        sys::memory_share(gpu_proc, content.content_pa, content.content_pages, true)
            .unwrap_or_else(|_| {
                sys::print(b"init: memory_share (render content) failed\n");
                sys::exit();
            }) as u64
    } else {
        0u64
    };

    let render_input_state_va = sys::memory_share(gpu_proc, mem.input_state_pa, 1, true)
        .unwrap_or_else(|_| {
            sys::print(b"init: memory_share (render input state) failed\n");
            sys::exit();
        });

    let render_cursor_state_va = sys::memory_share(gpu_proc, mem.cursor_state_pa, 1, true)
        .unwrap_or_else(|_| {
            sys::print(b"init: memory_share (render cursor state) failed\n");
            sys::exit();
        });

    // Send scene update channel endpoint B to render service.
    sys::handle_send(gpu_proc, cv_b.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-render B) failed\n");
        sys::exit();
    });

    // Start render service for display query.
    let gpu_ch = init_channel(gpu_channel_idx);
    let dev_config = DeviceConfig {
        mmio_pa: gpu_pa,
        irq: gpu_irq,
        init_handle: 0,
        service_handle: 0xFF,
        _pad: [0; 2],
    };
    // SAFETY: DeviceConfig fits within 60-byte payload; msg_type matches the payload type.
    let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &dev_config) };

    gpu_ch.send(&msg);

    sys::print(b"     starting ");
    sys::print(name);
    sys::print(b" (display query)\n");

    start_process(gpu_proc, b"render");

    // Wait for display info from render service (with timeout).
    sys::print(b"     waiting for display info\n");

    let mut resp_msg = ipc::Message::new(0);
    let mut display_ok = false;

    {
        let mut retries = 0u32;

        loop {
            match sys::wait(&[gpu_ch_handle.0], BOOT_TIMEOUT_NS) {
                Ok(_) => {
                    if gpu_ch.try_recv(&mut resp_msg) && resp_msg.msg_type == MSG_DISPLAY_INFO {
                        display_ok = true;
                        break;
                    }
                }
                Err(sys::SyscallError::WouldBlock) => {
                    retries += 1;
                    sys::print(b"init: timeout waiting for display info (retry)\n");
                    if retries >= 3 {
                        sys::print(b"init: FATAL - render service not responding (display info)\n");
                        break;
                    }
                }
                _ => break,
            }
        }
    }

    if !display_ok {
        sys::print(b"init: cannot continue without display info, halting\n");
        loop {
            sys::yield_now();
        }
    }

    let display_info = if let Some(protocol::gpu::Message::DisplayInfo(d)) =
        protocol::gpu::decode(resp_msg.msg_type, &resp_msg.payload)
    {
        d
    } else {
        sys::print(b"init: bad display info payload\n");
        loop {
            sys::yield_now();
        }
    };
    let fb_width = display_info.width;
    let fb_height = display_info.height;
    let frame_rate: u16 = if display_info.refresh_rate > 0 {
        display_info.refresh_rate as u16
    } else {
        60
    };

    let scale_factor: f32 = if fb_width >= 2048 { 2.0 } else { 1.0 };
    let logical_w = (fb_width as f32 / scale_factor) as u32;
    let logical_h = (fb_height as f32 / scale_factor) as u32;

    {
        let mut buf = [0u8; 40];
        let prefix = b"     display resolution: ";

        buf[..prefix.len()].copy_from_slice(prefix);

        let mut pos = prefix.len();

        pos += sys::format_u32(fb_width, &mut buf[pos..]);
        buf[pos] = b'x';
        pos += 1;
        pos += sys::format_u32(fb_height, &mut buf[pos..]);
        buf[pos] = b'\n';
        pos += 1;

        sys::print(&buf[..pos]);
    }

    // Send GPU config.
    let gpu_config = GpuConfig {
        mmio_pa: gpu_pa,
        irq: gpu_irq,
        _pad: 0,
        fb_width,
        fb_height,
        fb_size: fb_width * fb_height * FB_BPP,
        chunks_per_buf: 0,
        chunk_order: 0,
        _pad2: 0,
    };
    // SAFETY: GpuConfig fits within 60-byte payload; msg_type matches the payload type.
    let msg = unsafe { ipc::Message::from_payload(MSG_GPU_CONFIG, &gpu_config) };

    gpu_ch.send(&msg);

    let _ = sys::channel_signal(gpu_ch_handle);

    // Wait for GPU_READY (with timeout).
    let mut gpu_ready = false;

    {
        let mut retries = 0u32;

        loop {
            match sys::wait(&[gpu_ch_handle.0], BOOT_TIMEOUT_NS) {
                Ok(_) => {
                    if gpu_ch.try_recv(&mut resp_msg) && resp_msg.msg_type == MSG_GPU_READY {
                        gpu_ready = true;
                        break;
                    }
                }
                Err(sys::SyscallError::WouldBlock) => {
                    retries += 1;
                    sys::print(b"init: timeout waiting for GPU ready (retry)\n");
                    if retries >= 3 {
                        sys::print(b"init: FATAL - render service not responding (GPU ready)\n");
                        break;
                    }
                }
                _ => break,
            }
        }
    }

    if !gpu_ready {
        sys::print(b"init: cannot continue without GPU ready, halting\n");
        loop {
            sys::yield_now();
        }
    }

    // Send compositor config to render service.
    let render_config = CompositorConfig {
        scene_va: render_scene_va as u64,
        content_va: render_content_va,
        fb_width,
        fb_height,
        content_size: content.content_size,
        scale_factor,
        frame_rate,
        font_size: 18,
        screen_dpi: 96,
        _pad: 0,
        pointer_state_va: render_input_state_va as u64,
        cursor_state_va: render_cursor_state_va as u64,
    };
    // SAFETY: CompositorConfig fits within 60-byte payload; msg_type matches the payload type.
    let msg = unsafe { ipc::Message::from_payload(MSG_COMPOSITOR_CONFIG, &render_config) };

    gpu_ch.send(&msg);

    let _ = sys::channel_signal(gpu_ch_handle);

    sys::print(b"     render config sent to ");
    sys::print(name);
    sys::print(b"\n");

    (
        DisplayConfig {
            fb_width,
            fb_height,
            logical_w,
            logical_h,
            scale_factor,
            frame_rate,
        },
        cv_a,
    )
}

/// Spawn the view-engine (C) process and share all required memory regions.
///
/// Sends CoreConfig, FrameRateMsg, and CoreLayoutConfig. Does NOT start the
/// process — that happens in `start_all_processes()`.
///
/// Returns (process_handle, channel_index).
fn spawn_view_engine(
    mem: &PipelineMemory,
    content: &ContentInfo,
    doc_pa: u64,
    display: &DisplayConfig,
    rtc_pa: u64,
    input_device_count: usize,
    next_channel: &mut usize,
) -> (sys::ProcessHandle, usize) {
    let (core_proc, _core_ch_handle, core_channel_idx) =
        match spawn_with_channel(VIEW_ENGINE_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn view-engine\n");
                sys::exit();
            }
        };

    // Share document buffer with C (read-write — C writes header for cursor sync).
    let core_doc_va =
        sys::memory_share(core_proc, doc_pa, DOC_BUF_PAGES, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (core doc) failed\n");
            sys::exit();
        });
    // Share scene graph with C (read-write).
    let core_scene_va =
        sys::memory_share(core_proc, mem.scene_pa, mem.scene_page_count, false).unwrap_or_else(
            |_| {
                sys::print(b"init: memory_share (core scene) failed\n");
                sys::exit();
            },
        );
    // Share Content Region with C (read-only).
    let core_content_va = if content.content_pages > 0 {
        sys::memory_share(core_proc, content.content_pa, content.content_pages, true)
            .unwrap_or_else(|_| {
                sys::print(b"init: memory_share (core content) failed\n");
                sys::exit();
            }) as u64
    } else {
        0u64
    };
    // Share pointer state register with C (read-only).
    let core_input_state_va =
        sys::memory_share(core_proc, mem.input_state_pa, 1, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (core input state) failed\n");
            sys::exit();
        });
    // Share cursor state page with C (read-write — C writes shape data).
    let core_cursor_state_va =
        sys::memory_share(core_proc, mem.cursor_state_pa, 1, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (core cursor state) failed\n");
            sys::exit();
        });
    // Share layout results with C (read-only — C consumes layout from B).
    let core_layout_results_va = sys::memory_share(
        core_proc,
        mem.layout_results_pa,
        mem.layout_results_pages,
        true,
    )
    .unwrap_or_else(|_| {
        sys::print(b"init: memory_share (layout results to C) failed\n");
        sys::exit();
    });
    // Share viewport state with C (read-write — C writes viewport params).
    let core_viewport_state_va =
        sys::memory_share(core_proc, mem.viewport_state_pa, 1, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (viewport state to C) failed\n");
            sys::exit();
        });

    // Send core config.
    let core_ch = init_channel(core_channel_idx);
    let core_config = CoreConfig {
        doc_va: core_doc_va as u64,
        scene_va: core_scene_va as u64,
        content_va: core_content_va,
        input_state_va: core_input_state_va as u64,
        fb_width: display.logical_w,
        fb_height: display.logical_h,
        doc_capacity: DOC_BUF_CAPACITY,
        content_size: content.content_size,
        cursor_state_va: core_cursor_state_va as u64,
    };
    // SAFETY: CoreConfig fits within 60-byte payload; msg_type matches the payload type.
    let msg = unsafe { ipc::Message::from_payload(MSG_CORE_CONFIG, &core_config) };
    core_ch.send(&msg);

    // Send frame rate as a separate message.
    let fr_msg = unsafe {
        ipc::Message::from_payload(
            MSG_FRAME_RATE,
            &FrameRateMsg {
                frame_rate: display.frame_rate as u32,
            },
        )
    };
    core_ch.send(&fr_msg);

    // Send layout config with handle assignments.
    // Handle order is determined by handle_send calls in wire_service_channels():
    //   1=input, 2=compositor, 3=editor, 4=document-model, 5=layout-engine, 6+=additional inputs
    let core_layout_config = CoreLayoutConfig {
        layout_results_va: core_layout_results_va as u64,
        layout_results_capacity: mem.layout_results_size as u32,
        viewport_state_va: core_viewport_state_va as u64,
        input_handle: 1,
        compositor_handle: 2,
        editor_handle: 3,
        docmodel_handle: 4,
        layout_handle: 5,
        input2_handle: if input_device_count > 1 { 6 } else { 0xFF },
        _pad: [0; 2],
    };
    // SAFETY: CoreLayoutConfig fits within 60-byte payload.
    let cl_msg =
        unsafe { ipc::Message::from_payload(MSG_CORE_LAYOUT_CONFIG, &core_layout_config) };
    core_ch.send(&cl_msg);

    // Send RTC config to core.
    if rtc_pa != 0 {
        let rtc_config = RtcConfig { mmio_pa: rtc_pa };
        // SAFETY: RtcConfig fits within 60-byte payload; msg_type matches the payload type.
        let rtc_msg = unsafe { ipc::Message::from_payload(MSG_RTC_CONFIG, &rtc_config) };

        core_ch.send(&rtc_msg);

        sys::print(b"     rtc config sent to core\n");
    }

    (core_proc, core_channel_idx)
}

/// Spawn the document-model (A) process and share required memory.
///
/// A owns the document buffer (read-write) and manages decoded images
/// in the Content Region. Config includes handle assignments for
/// editor, decoder, document service, and core channels.
///
/// Returns (process_handle, channel_index).
fn spawn_document_model(
    content: &ContentInfo,
    doc_pa: u64,
    next_channel: &mut usize,
) -> (sys::ProcessHandle, usize) {
    sys::print(b"     spawning document-model\n");
    let (docmodel_proc, _docmodel_ch_handle, docmodel_ch_idx) =
        match spawn_with_channel(DOCUMENT_MODEL_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn document-model\n");
                sys::exit();
            }
        };

    // Share document buffer with A (read-write — A is sole content writer).
    let docmodel_doc_va =
        sys::memory_share(docmodel_proc, doc_pa, DOC_BUF_PAGES, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (docmodel doc) failed\n");
            sys::exit();
        });
    // Share Content Region with A (read-write — A manages decoded images).
    let docmodel_content_va = if content.content_pages > 0 {
        sys::memory_share(docmodel_proc, content.content_pa, content.content_pages, false)
            .unwrap_or_else(|_| {
                sys::print(b"init: memory_share (docmodel content) failed\n");
                sys::exit();
            }) as u64
    } else {
        0u64
    };

    // Send document-model config with handle assignments.
    // Handle order determined by handle_send calls in wire_service_channels():
    //   1=editor, 2=decoder, 3=document-service, 4=core
    let docmodel_ch = init_channel(docmodel_ch_idx);
    let docmodel_config = protocol::document_model::DocModelConfig {
        doc_va: docmodel_doc_va as u64,
        doc_capacity: DOC_BUF_CAPACITY,
        content_va: docmodel_content_va,
        content_size: content.content_size,
        img_file_store_offset: content.png_offset,
        img_file_store_length: content.png_len,
        editor_handle: 1,
        decoder_handle: 2,
        fs_handle: 3,
        core_handle: 4,
    };
    let dm_msg = unsafe {
        ipc::Message::from_payload(
            protocol::document_model::MSG_DOC_MODEL_CONFIG,
            &docmodel_config,
        )
    };
    docmodel_ch.send(&dm_msg);

    (docmodel_proc, docmodel_ch_idx)
}

/// Spawn the layout-engine (B) process and share required memory.
///
/// B reads the document buffer (RO), Content Region (RO, fonts),
/// writes layout results (RW), and reads viewport state (RO).
///
/// Returns (process_handle, channel_index).
fn spawn_layout_engine(
    mem: &PipelineMemory,
    content: &ContentInfo,
    doc_pa: u64,
    next_channel: &mut usize,
) -> (sys::ProcessHandle, usize) {
    sys::print(b"     spawning layout-engine\n");
    let (layout_proc, _layout_ch_handle, layout_ch_idx) =
        match spawn_with_channel(LAYOUT_ENGINE_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn layout-engine\n");
                sys::exit();
            }
        };

    // Share document buffer with B (read-only).
    let layout_doc_va =
        sys::memory_share(layout_proc, doc_pa, DOC_BUF_PAGES, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (layout doc) failed\n");
            sys::exit();
        });
    // Share Content Region with B (read-only — fonts).
    let layout_content_va = if content.content_pages > 0 {
        sys::memory_share(layout_proc, content.content_pa, content.content_pages, true)
            .unwrap_or_else(|_| {
                sys::print(b"init: memory_share (layout content) failed\n");
                sys::exit();
            }) as u64
    } else {
        0u64
    };
    // Share layout results with B (read-write — B produces layout).
    let layout_results_b_va = sys::memory_share(
        layout_proc,
        mem.layout_results_pa,
        mem.layout_results_pages,
        false,
    )
    .unwrap_or_else(|_| {
        sys::print(b"init: memory_share (layout results to B) failed\n");
        sys::exit();
    });
    // Share viewport state with B (read-only — C writes, B reads).
    let layout_viewport_va =
        sys::memory_share(layout_proc, mem.viewport_state_pa, 1, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (viewport state to B) failed\n");
            sys::exit();
        });

    // Send LayoutEngineConfig to B.
    // Handle assignment: 1=core (determined by wire_service_channels).
    let layout_ch = init_channel(layout_ch_idx);
    let layout_config = LayoutEngineConfig {
        doc_va: layout_doc_va as u64,
        content_va: layout_content_va,
        layout_results_va: layout_results_b_va as u64,
        viewport_state_va: layout_viewport_va as u64,
        doc_capacity: DOC_BUF_CAPACITY,
        content_size: content.content_size,
        layout_results_capacity: mem.layout_results_size as u32,
        core_handle: 1,
        _pad: [0; 3],
    };
    let layout_msg =
        // SAFETY: LayoutEngineConfig fits within 60-byte payload.
        unsafe { ipc::Message::from_payload(MSG_LAYOUT_ENGINE_CONFIG, &layout_config) };
    layout_ch.send(&layout_msg);
    sys::print(b"     layout-engine config sent\n");

    (layout_proc, layout_ch_idx)
}

/// Wire the first input device channel to the view-engine (C) and configure
/// the input driver. Additional input devices are wired in `wire_additional_inputs()`.
fn spawn_input_drivers(
    input_devices: &[(sys::ProcessHandle, usize, u64, u32)],
    core_proc: sys::ProcessHandle,
    mem: &PipelineMemory,
    next_channel: &mut usize,
) {
    if input_devices.is_empty() {
        return;
    }

    let (input_proc_handle, input_ch_idx, input_pa, input_irq) = input_devices[0];

    sys::print(b"     creating input\xE2\x86\x92core channel\n");

    let (ic_a, ic_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (input-core) failed\n");
        sys::exit();
    });

    *next_channel += 1;

    sys::handle_send(input_proc_handle, ic_a.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (input-core A) failed\n");
        sys::exit();
    });
    // Send to C (first handle after init channel).
    sys::handle_send(core_proc, ic_b.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (input-core B) failed\n");
        sys::exit();
    });

    let input_ch = init_channel(input_ch_idx);
    let input_config = DeviceConfig {
        mmio_pa: input_pa,
        irq: input_irq,
        init_handle: 0,
        service_handle: 1,
        _pad: [0; 2],
    };
    // SAFETY: same as DeviceConfig from_payload above.
    let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &input_config) };

    input_ch.send(&msg);

    // Share pointer state register with input driver (read-write).
    let driver_input_state_va =
        sys::memory_share(input_proc_handle, mem.input_state_pa, 1, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (input state to driver) failed\n");
            sys::exit();
        });
    let state_config = protocol::input::PointerStateConfig {
        state_va: driver_input_state_va as u64,
    };
    // SAFETY: PointerStateConfig fits within 60-byte payload.
    let state_msg = unsafe {
        ipc::Message::from_payload(protocol::input::MSG_POINTER_STATE_CONFIG, &state_config)
    };
    input_ch.send(&state_msg);

    sys::print(b"     input device 0 channel created\n");
}

/// Spawn the rich editor process with document buffer (read-only).
///
/// Returns (process_handle, channel_index).
fn spawn_editor(doc_pa: u64, next_channel: &mut usize) -> (sys::ProcessHandle, usize) {
    sys::print(b"     spawning rich editor\n");

    let (editor_proc, _editor_ch, editor_ch_idx) =
        match spawn_with_channel(RICH_EDITOR_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn rich editor\n");
                sys::exit();
            }
        };

    // Share document buffer with editor (read-only).
    let editor_doc_va =
        sys::memory_share(editor_proc, doc_pa, DOC_BUF_PAGES, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (editor doc) failed\n");
            sys::exit();
        });
    let editor_ch = init_channel(editor_ch_idx);
    let editor_config = EditorConfig {
        doc_va: editor_doc_va as u64,
        doc_capacity: DOC_BUF_CAPACITY,
        _pad: 0,
    };
    // SAFETY: EditorConfig fits within 60-byte payload; msg_type matches the payload type.
    let msg = unsafe { ipc::Message::from_payload(MSG_EDITOR_CONFIG, &editor_config) };

    editor_ch.send(&msg);

    (editor_proc, editor_ch_idx)
}

/// Wire all cross-process IPC channels between services.
///
/// Creates and sends channel endpoints for:
/// - C → render (scene update channel endpoint A)
/// - C ↔ editor
/// - editor ↔ A (document writes)
/// - A ↔ decoder (image decode, if available)
/// - A ↔ document service (persistence)
/// - A ↔ C (notifications, undo/redo)
/// - B ↔ C (layout recompute/ready)
/// - Additional input devices → C
fn wire_service_channels(
    core_proc: sys::ProcessHandle,
    editor_proc: sys::ProcessHandle,
    docmodel_proc: sys::ProcessHandle,
    layout_proc: sys::ProcessHandle,
    cv_a: sys::ChannelHandle,
    content: &ContentInfo,
    mem: &PipelineMemory,
    fs_info: Option<(sys::ProcessHandle, sys::ChannelHandle, usize, u64, u32)>,
    fs_started: bool,
    doc_core_ch: Option<sys::ChannelHandle>,
    doc_pa: u64,
    input_devices: &[(sys::ProcessHandle, usize, u64, u32)],
    next_channel: &mut usize,
) -> Option<sys::ProcessHandle> {
    // Scene update channel endpoint A → C.
    sys::handle_send(core_proc, cv_a.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-render A) failed\n");
        sys::exit();
    });

    // C ↔ editor channel.
    sys::print(b"     creating core\xE2\x86\x94editor channel\n");

    let (ce_a, ce_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (core-editor) failed\n");
        sys::exit();
    });

    *next_channel += 1;

    sys::handle_send(core_proc, ce_a.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-editor A) failed\n");
        sys::exit();
    });
    sys::handle_send(editor_proc, ce_b.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (core-editor B) failed\n");
        sys::exit();
    });

    // Editor ↔ A channel (editor sends write operations to document-model).
    sys::print(b"     creating editor\xE2\x86\x94document-model channel\n");

    let (ea_a, ea_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (editor-docmodel) failed\n");
        sys::exit();
    });

    *next_channel += 1;

    sys::handle_send(docmodel_proc, ea_a.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (editor-docmodel A) failed\n");
        sys::exit();
    });
    sys::handle_send(editor_proc, ea_b.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (editor-docmodel B) failed\n");
        sys::exit();
    });

    // A ↔ Decoder channel (if content and file store are available).
    let decoder_proc = if content.content_pages > 0 && content.file_store_pages > 0 {
        sys::print(b"     spawning png-decode\n");
        match spawn_with_channel(PNG_DECODE_ELF, next_channel) {
            Some((dec_proc, _dec_ch, dec_ch_idx)) => {
                // Share File Store (read-only) and Content Region (read-write).
                let dec_fs_va = sys::memory_share(
                    dec_proc,
                    content.file_store_pa,
                    content.file_store_pages,
                    true,
                )
                .unwrap_or_else(|_| {
                    sys::print(b"init: memory_share (decoder file store) failed\n");
                    sys::exit();
                });
                let dec_content_va = sys::memory_share(
                    dec_proc,
                    content.content_pa,
                    content.content_pages,
                    false,
                )
                .unwrap_or_else(|_| {
                    sys::print(b"init: memory_share (decoder content) failed\n");
                    sys::exit();
                });

                // Send DecoderConfig on the init↔decoder channel.
                let dec_ch = init_channel(dec_ch_idx);
                let dec_config = protocol::decode::DecoderConfig {
                    file_store_va: dec_fs_va as u64,
                    file_store_size: (content.file_store_pages as u32) * PAGE_SIZE as u32,
                    content_va: dec_content_va as u64,
                    content_size: content.content_size,
                };
                let dec_msg = unsafe {
                    ipc::Message::from_payload(protocol::decode::MSG_DECODER_CONFIG, &dec_config)
                };
                dec_ch.send(&dec_msg);

                // A ↔ decoder channel.
                sys::print(b"     creating docmodel\xE2\x86\x94decoder channel\n");
                let (dc_a, dc_b) = sys::channel_create().unwrap_or_else(|_| {
                    sys::print(b"init: channel_create (docmodel-decoder) failed\n");
                    sys::exit();
                });
                *next_channel += 1;

                sys::handle_send(docmodel_proc, dc_a.0).unwrap_or_else(|_| {
                    sys::print(b"init: handle_send (docmodel-decoder A) failed\n");
                    sys::exit();
                });
                sys::handle_send(dec_proc, dc_b.0).unwrap_or_else(|_| {
                    sys::print(b"init: handle_send (docmodel-decoder B) failed\n");
                    sys::exit();
                });

                Some(dec_proc)
            }
            None => {
                sys::print(b"init: failed to spawn png-decode\n");
                None
            }
        }
    } else {
        None
    };

    // A ↔ Document service channel.
    if let Some((fs_proc, fs_ch, fs_ch_idx, fs_pa, fs_irq)) = fs_info {
        sys::print(b"     creating docmodel\xE2\x86\x94document channel\n");

        if fs_started {
            // Document service already running (started during font loading).
            // Channel was pre-created; endpoint B already sent to doc.
            // Send endpoint A to A.
            if let Some(ch_a) = doc_core_ch {
                sys::handle_send(docmodel_proc, ch_a.0).unwrap_or_else(|_| {
                    sys::print(b"init: handle_send (docmodel-doc A) failed\n");
                    sys::exit();
                });
            }
        } else {
            // Document service not yet started — share memory and send config.
            let fs_doc_va = sys::memory_share(fs_proc, doc_pa, DOC_BUF_PAGES, false)
                .unwrap_or_else(|_| {
                    sys::print(b"init: memory_share (doc) failed\n");
                    sys::exit();
                });

            let fs_ch_obj = init_channel(fs_ch_idx);
            let doc_config = protocol::document::DocConfig {
                mmio_pa: fs_pa,
                irq: fs_irq,
                _pad: 0,
                doc_va: fs_doc_va as u64,
                doc_capacity: DOC_BUF_CAPACITY,
                _pad2: 0,
                content_va: 0,
                content_size: 0,
                init_handle: 0,
                core_handle: 1,
                _pad3: [0; 2],
            };
            let doc_msg = unsafe {
                ipc::Message::from_payload(protocol::document::MSG_DOC_CONFIG, &doc_config)
            };
            fs_ch_obj.send(&doc_msg);

            // Create A ↔ document service channel.
            let (cf_a, cf_b) = sys::channel_create().unwrap_or_else(|_| {
                sys::print(b"init: channel_create (docmodel-doc) failed\n");
                sys::exit();
            });
            *next_channel += 1;

            sys::handle_send(docmodel_proc, cf_a.0).unwrap_or_else(|_| {
                sys::print(b"init: handle_send (docmodel-doc A) failed\n");
                sys::exit();
            });
            sys::handle_send(fs_proc, cf_b.0).unwrap_or_else(|_| {
                sys::print(b"init: handle_send (docmodel-doc B) failed\n");
                sys::exit();
            });
        }
    }

    // A ↔ C notification channel.
    sys::print(b"     creating docmodel\xE2\x86\x94core channel\n");
    let (ac_a, ac_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (docmodel-core) failed\n");
        sys::exit();
    });
    *next_channel += 1;

    sys::handle_send(core_proc, ac_a.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (docmodel-core A) failed\n");
        sys::exit();
    });
    sys::handle_send(docmodel_proc, ac_b.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (docmodel-core B) failed\n");
        sys::exit();
    });

    // B ↔ C channel (layout-engine ↔ view-engine).
    // Must be sent before additional input devices.
    sys::print(b"     creating layout-engine\xE2\x86\x94core channel\n");
    let (bc_a, bc_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (layout-core) failed\n");
        sys::exit();
    });
    *next_channel += 1;

    sys::handle_send(layout_proc, bc_a.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (layout-core A) failed\n");
        sys::exit();
    });
    sys::handle_send(core_proc, bc_b.0).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (layout-core B) failed\n");
        sys::exit();
    });

    // Additional input device channels → C (handle 6+).
    // Must come AFTER B↔C channel so that handle 5 = layout-engine.
    for i in 1..input_devices.len() {
        let (input_proc_handle, input_ch_idx, input_pa, input_irq) = input_devices[i];

        sys::print(b"     creating input\xE2\x86\x92core channel\n");

        let (ic_a, ic_b) = sys::channel_create().unwrap_or_else(|_| {
            sys::print(b"init: channel_create (input-core) failed\n");
            sys::exit();
        });

        *next_channel += 1;

        sys::handle_send(input_proc_handle, ic_a.0).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-core A) failed\n");
            sys::exit();
        });
        sys::handle_send(core_proc, ic_b.0).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-core B) failed\n");
            sys::exit();
        });

        let input_ch = init_channel(input_ch_idx);
        let input_config = DeviceConfig {
            mmio_pa: input_pa,
            irq: input_irq,
            init_handle: 0,
            service_handle: 1,
            _pad: [0; 2],
        };
        // SAFETY: same as DeviceConfig from_payload above.
        let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &input_config) };

        input_ch.send(&msg);

        // Share pointer state register with additional input driver.
        let drv_state_va = sys::memory_share(input_proc_handle, mem.input_state_pa, 1, false)
            .unwrap_or_else(|_| {
                sys::print(b"init: memory_share (input state to driver) failed\n");
                sys::exit();
            });
        let sc = protocol::input::PointerStateConfig {
            state_va: drv_state_va as u64,
        };
        let sm =
            unsafe { ipc::Message::from_payload(protocol::input::MSG_POINTER_STATE_CONFIG, &sc) };
        input_ch.send(&sm);
    }

    decoder_proc
}

/// Start all processes in dependency order.
///
/// Order: decoder → document service → input drivers → editor →
///        document-model → layout-engine → view-engine.
/// Document-model must start before view-engine (A loads document, C waits).
/// Decoder must start before A (A sends decode request at boot).
/// Document service must start before A (A queries documents at boot).
fn start_all_processes(
    name: &[u8],
    decoder_proc: Option<sys::ProcessHandle>,
    fs_info: Option<(sys::ProcessHandle, sys::ChannelHandle, usize, u64, u32)>,
    fs_started: bool,
    input_devices: &[(sys::ProcessHandle, usize, u64, u32)],
    editor_proc: sys::ProcessHandle,
    docmodel_proc: sys::ProcessHandle,
    layout_proc: sys::ProcessHandle,
    core_proc: sys::ProcessHandle,
) {
    if let Some(dec_proc) = decoder_proc {
        sys::print(b"     starting png-decode\n");
        start_process(dec_proc, b"png-decode");
        sys::yield_now();
    }

    if let Some((fs_proc, _, _, _, _)) = fs_info {
        if !fs_started {
            sys::print(b"     starting document service\n");
            start_process(fs_proc, b"document");
            sys::yield_now();
        }
    }

    for &(input_proc_handle, _, _, _) in input_devices {
        sys::print(b"     starting input driver\n");

        start_process(input_proc_handle, b"input");

        sys::yield_now();
    }

    sys::print(b"     starting rich editor\n");

    start_process(editor_proc, b"editor");

    sys::yield_now();

    sys::print(b"     starting document-model\n");

    start_process(docmodel_proc, b"document-model");

    sys::yield_now();

    sys::print(b"     starting layout-engine\n");

    start_process(layout_proc, b"layout-engine");

    sys::yield_now();

    sys::print(b"     starting view-engine\n");

    start_process(core_proc, b"view-engine");

    sys::yield_now();

    sys::print(b"     ");
    sys::print(name);
    sys::print(b" pipeline running\n");
}

// ---------------------------------------------------------------------------
// Phase 2: Render pipeline orchestrator
// ---------------------------------------------------------------------------

/// Set up the full render pipeline: allocate shared memory, configure the
/// render service, spawn all processes (A, B, C, editor, decoder), wire
/// cross-process channels, and start everything in dependency order.
///
/// Returns (core_proc_handle, editor_proc_handle).
fn spawn_render_pipeline(
    name: &[u8],
    gpu_proc: sys::ProcessHandle,
    gpu_ch_handle: sys::ChannelHandle,
    gpu_channel_idx: usize,
    gpu_pa: u64,
    gpu_irq: u32,
    input_devices: &[(sys::ProcessHandle, usize, u64, u32)],
    content_region: Option<(u64, u32)>,
    file_store: Option<(u64, u32, u32)>,
    rtc_pa: u64,
    fs_info: Option<(sys::ProcessHandle, sys::ChannelHandle, usize, u64, u32)>,
    doc_buf: (u64, usize),
    fs_started: bool,
    doc_core_ch: Option<sys::ChannelHandle>,
    next_channel: &mut usize,
) -> (sys::ProcessHandle, sys::ProcessHandle) {
    sys::print(b"     setting up ");
    sys::print(name);
    sys::print(b" pipeline\n");

    let (doc_pa, _doc_va) = doc_buf;

    // Unpack content and file store info.
    let content = ContentInfo::from_options(content_region, file_store);

    sys::print(b"     document buffer: 4 KiB shared\n");

    // Step 1: Allocate all shared memory regions.
    let mem = allocate_shared_regions();

    // Step 2: Configure render service (GPU handshake, display query, compositor config).
    let (display, cv_a) = configure_render_service(
        name,
        gpu_proc,
        gpu_ch_handle,
        gpu_channel_idx,
        gpu_pa,
        gpu_irq,
        &mem,
        &content,
        next_channel,
    );

    // Step 3: Spawn view-engine (C).
    let (core_proc, _core_ch_idx) = spawn_view_engine(
        &mem,
        &content,
        doc_pa,
        &display,
        rtc_pa,
        input_devices.len(),
        next_channel,
    );

    // Step 4: Spawn document-model (A).
    let (docmodel_proc, _docmodel_ch_idx) =
        spawn_document_model(&content, doc_pa, next_channel);

    // Step 5: Spawn layout-engine (B).
    let (layout_proc, _layout_ch_idx) =
        spawn_layout_engine(&mem, &content, doc_pa, next_channel);

    // Step 6: Wire first input device to C.
    spawn_input_drivers(input_devices, core_proc, &mem, next_channel);

    // Step 7: Spawn editor.
    let (editor_proc, _editor_ch_idx) = spawn_editor(doc_pa, next_channel);

    // Step 8: Wire all cross-process channels.
    let decoder_proc = wire_service_channels(
        core_proc,
        editor_proc,
        docmodel_proc,
        layout_proc,
        cv_a,
        &content,
        &mem,
        fs_info,
        fs_started,
        doc_core_ch,
        doc_pa,
        input_devices,
        next_channel,
    );

    // Step 9: Start all processes in dependency order.
    start_all_processes(
        name,
        decoder_proc,
        fs_info,
        fs_started,
        input_devices,
        editor_proc,
        docmodel_proc,
        layout_proc,
        core_proc,
    );

    (core_proc, editor_proc)
}

// ---------------------------------------------------------------------------
// Phase 3: Post-boot monitoring
// ---------------------------------------------------------------------------

/// Monitor child processes after boot — detect and report crashes.
///
/// Uses `sys::wait()` to block until a child exits, logs the exit,
/// and removes it from the watch list. Continues until all children
/// have exited.
fn monitor_children(services: &mut [ServiceDescriptor; MAX_SERVICES], service_count: &mut usize) {
    if *service_count == 0 {
        return;
    }

    sys::print(b"  init: monitoring child processes\n");

    // Build handle + name arrays from service descriptors.
    let mut handles: [u8; MAX_SERVICES] = [0; MAX_SERVICES];
    let mut count = 0usize;
    for i in 0..*service_count {
        if services[i].active {
            handles[count] = services[i].process.0;
            count += 1;
        }
    }

    loop {
        match sys::wait(&handles[..count], u64::MAX) {
            Ok(idx) => {
                // Find the matching service descriptor for logging.
                let mut desc_idx = 0usize;
                let mut found = false;
                for i in 0..*service_count {
                    if services[i].active && services[i].process.0 == handles[idx] {
                        desc_idx = i;
                        found = true;
                        break;
                    }
                }

                sys::print(b"  init: CHILD PROCESS EXITED: ");
                if found {
                    sys::print(services[desc_idx].name);
                    services[desc_idx].active = false;
                } else {
                    sys::print(b"unknown");
                }
                sys::print(b"\n");

                // Remove exited handle by swapping with last.
                count -= 1;
                if idx < count {
                    handles[idx] = handles[count];
                }

                if count == 0 {
                    sys::print(b"  init: all child processes exited\n");
                    break;
                }
            }
            Err(_) => {
                // Spurious wakeup — continue monitoring.
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

#[unsafe(no_mangle)]
pub extern "C" fn _start() -> ! {
    sys::print(b"  \xF0\x9F\x94\xA7 init - proto-os-service starting\n");

    // Track channel allocation (0 = kernel, 1+ = ours).
    let mut next_channel: usize = 1;

    // Service descriptor table — retained after boot for monitoring and restart.
    let mut services = [const { ServiceDescriptor::empty() }; MAX_SERVICES];
    let mut service_count: usize = 0;

    // Phase 1: Parse device manifest and spawn driver processes.
    let manifest = parse_device_manifest(&mut next_channel);

    // Phase 1.5: Allocate document buffer and load fonts.
    let (doc_pa, doc_va) = allocate_document_buffer();

    let font_result = if let Some((fs_proc, fs_ch, fs_ch_idx, fs_pa, fs_irq)) = manifest.fs_dev {
        load_fonts_native(
            fs_proc,
            fs_ch,
            fs_ch_idx,
            fs_pa,
            fs_irq,
            doc_pa,
            &mut next_channel,
        )
    } else if let Some((p9_proc, p9_ch, p9_ch_idx, p9_pa, p9_irq)) = manifest.p9 {
        load_fonts_9p(p9_proc, p9_ch, p9_ch_idx, p9_pa, p9_irq)
    } else {
        FontLoadResult {
            content_region_info: None,
            file_store_info: None,
            fs_started: false,
            doc_core_ch_a: None,
        }
    };

    // Phase 2: Set up the render pipeline.
    if let Some((gpu_proc, gpu_ch_handle, gpu_channel_idx, gpu_pa, gpu_irq, render_type)) =
        manifest.gpu
    {
        let render_name: &[u8] = match render_type {
            2 => b"metal",
            1 => b"virgl",
            _ => b"cpu-render",
        };
        let (core_proc, editor_proc) = spawn_render_pipeline(
            render_name,
            gpu_proc,
            gpu_ch_handle,
            gpu_channel_idx,
            gpu_pa,
            gpu_irq,
            &manifest.input_devices[..manifest.input_count],
            font_result.content_region_info,
            font_result.file_store_info,
            manifest.rtc_pa,
            manifest.fs_dev,
            (doc_pa, doc_va),
            font_result.fs_started,
            font_result.doc_core_ch_a,
            &mut next_channel,
        );

        // Register all spawned services in the descriptor table.
        // Render service.
        services[service_count] = ServiceDescriptor {
            name: render_name,
            process: gpu_proc,
            active: true,
        };
        service_count += 1;

        // View-engine (C).
        services[service_count] = ServiceDescriptor {
            name: b"view-engine",
            process: core_proc,
            active: true,
        };
        service_count += 1;

        // Editor.
        services[service_count] = ServiceDescriptor {
            name: b"editor",
            process: editor_proc,
            active: true,
        };
        service_count += 1;

        // Input drivers.
        for i in 0..manifest.input_count {
            if service_count < MAX_SERVICES {
                services[service_count] = ServiceDescriptor {
                    name: b"input",
                    process: manifest.input_devices[i].0,
                    active: true,
                };
                service_count += 1;
            }
        }

        // 9P driver (only if not using native fs).
        if !font_result.fs_started {
            if let Some((p9_proc, _, _, _, _)) = manifest.p9 {
                if service_count < MAX_SERVICES {
                    services[service_count] = ServiceDescriptor {
                        name: b"9p",
                        process: p9_proc,
                        active: true,
                    };
                    service_count += 1;
                }
            }
        }

        // Document service.
        if let Some((fs_proc, _, _, _, _)) = manifest.fs_dev {
            if service_count < MAX_SERVICES {
                services[service_count] = ServiceDescriptor {
                    name: b"document",
                    process: fs_proc,
                    active: true,
                };
                service_count += 1;
            }
        }
    } else {
        sys::print(b"     no gpu found\n");
    }

    // If no GPU device was found, run headless tests.
    if manifest.gpu.is_none() {
        sys::print(b"     no gpu found, running headless tests\n");

        // Fuzz test — adversarial syscall testing.
        match sys::process_create(FUZZ_ELF.as_ptr(), FUZZ_ELF.len()) {
            Ok(proc_h) => {
                start_process(proc_h, b"fuzz");
                let _ = sys::wait(&[proc_h.0], u64::MAX);
            }
            Err(_) => {
                sys::print(b"     fuzz test spawn failed\n");
            }
        }
        // Stress test — IPC/scheduler/timer saturation.
        match sys::process_create(STRESS_ELF.as_ptr(), STRESS_ELF.len()) {
            Ok(proc_h) => {
                start_process(proc_h, b"stress");
                let _ = sys::wait(&[proc_h.0], u64::MAX);
            }
            Err(_) => {
                sys::print(b"     stress test spawn failed\n");
            }
        }
    }

    // Phase 3: Monitor child processes — detect and report crashes.
    monitor_children(&mut services, &mut service_count);

    sys::print(b"  init: no children left, idling\n");

    // Nothing left to monitor.
    loop {
        sys::yield_now();
    }
}
