//! Init — proto-OS-service.
//!
//! The kernel spawns only init. Init reads a device manifest from the kernel
//! via channel shared memory, then spawns and orchestrates all other userspace
//! processes: virtio drivers, compositor, etc.
//!
//! This is the microkernel pattern: kernel provides mechanism, init provides
//! policy. Matches Fuchsia's component_manager, seL4's root task, QNX's procnto.
//!
//! # IPC topology
//!
//! Init creates three kinds of channels:
//!
//! 1. **Config channels** (init ↔ child) — one per child process. Init sends
//!    configuration as the first ring buffer message before starting the child.
//!
//! 2. **Input channel** (input driver → compositor) — carries keyboard events.
//!    Init creates the channel, sends endpoint A to the input driver and
//!    endpoint B to the compositor. The driver produces, compositor consumes.
//!
//! 3. **Present channel** (compositor → GPU driver) — carries frame present
//!    commands. Compositor produces, GPU driver consumes.
//!
//! # Kernel channel (raw bytes, not ring buffer)
//!
//! The kernel writes the device manifest as raw bytes before starting init.
//! The kernel doesn't use the ipc library — it writes directly to the shared
//! page. This is the only non-ring-buffer channel in the system.
//!
//! ```text
//! offset 0:  device_count (u32)
//! offset 4:  _padding     (u32)
//! offset 8:  device[0]: { pa: u64, irq: u32, device_id: u32 }  (16 bytes)
//! offset 24: device[1]: ...
//! ```

#![no_std]
#![no_main]

// ELF binaries for all processes that init can spawn.
// Generated by build.rs and included via env var at compile time.
include!(env!("INIT_EMBEDDED_RS"));

/// Channel shared memory base. The kernel's channel is at page 0.
/// Channels created by init are at subsequent 2-page pairs.
const CHANNEL_SHM_BASE: usize = 0x4000_0000;
/// Framebuffer dimensions (matches QEMU virtio-gpu default).
const FB_WIDTH: u32 = 1024;
const FB_HEIGHT: u32 = 768;
const FB_BPP: u32 = 4;
const FB_STRIDE: u32 = FB_WIDTH * FB_BPP;
const FB_SIZE: u32 = FB_STRIDE * FB_HEIGHT;
/// Virtio device IDs (must match kernel probe).
const VIRTIO_DEVICE_BLK: u32 = 2;
const VIRTIO_DEVICE_CONSOLE: u32 = 3;
const VIRTIO_DEVICE_GPU: u32 = 16;
const VIRTIO_DEVICE_INPUT: u32 = 18;
const VIRTIO_DEVICE_9P: u32 = 9;
/// Document buffer: 1 page. First 64 bytes = header, rest = content.
const DOC_BUF_PAGES: u64 = 1;
const DOC_BUF_HEADER: u32 = 64;
const DOC_BUF_CAPACITY: u32 = (DOC_BUF_PAGES as u32 * 4096) - DOC_BUF_HEADER;
// --- Protocol message types (shared with receivers) ---
const MSG_DEVICE_CONFIG: u32 = 1;
const MSG_GPU_CONFIG: u32 = 2;
const MSG_COMPOSITOR_CONFIG: u32 = 3;
const MSG_EDITOR_CONFIG: u32 = 4;
const MSG_FS_READ_REQUEST: u32 = 40;
const MSG_FS_READ_RESPONSE: u32 = 41;

#[repr(C)]
#[derive(Clone, Copy)]
struct CompositorConfig {
    fb_va: u64,
    fb_va2: u64,
    fb_width: u32,
    fb_height: u32,
    fb_stride: u32,
    fb_size: u32,
    doc_va: u64,
    doc_capacity: u32,
    font_len: u32,
    font_va: u64,
}

#[repr(C)]
#[derive(Clone, Copy)]
struct EditorConfig {
    doc_va: u64,
    doc_capacity: u32,
    _pad: u32,
}
#[repr(C)]
#[derive(Clone, Copy)]
struct DeviceConfig {
    mmio_pa: u64,
    irq: u32,
    _pad: u32,
}
#[repr(C)]
#[derive(Clone, Copy)]
struct GpuConfig {
    mmio_pa: u64,
    irq: u32,
    _pad: u32,
    fb_pa: u64,
    fb_pa2: u64,
    fb_width: u32,
    fb_height: u32,
    fb_size: u32,
    _pad2: u32,
}

/// Compute the base VA of channel N's shared pages in init's address space.
/// Each channel occupies 2 consecutive pages (one per direction).
/// Channel 0 = kernel channel, channel 1+ = channels created by init.
fn channel_shm_va(channel_index: usize) -> usize {
    CHANNEL_SHM_BASE + channel_index * 2 * 4096
}
/// Create an IPC channel for a given channel index. Init is always endpoint 0.
fn init_channel(channel_index: usize) -> ipc::Channel {
    let ch = unsafe { ipc::Channel::from_base(channel_shm_va(channel_index), ipc::PAGE_SIZE, 0) };

    ch.init();

    ch
}
fn print_u32(mut n: u32) {
    if n == 0 {
        sys::print(b"0");

        return;
    }

    let mut buf = [0u8; 10];
    let mut i = 10;

    while n > 0 {
        i -= 1;
        buf[i] = b'0' + (n % 10) as u8;
        n /= 10;
    }

    sys::print(&buf[i..]);
}
/// Set up the interactive display pipeline with input.
///
/// Creates cross-process channels:
/// - input driver → compositor (keyboard events)
/// - compositor → GPU driver (present commands)
///
/// Then starts all three processes. They run their own event loops.
fn setup_display_pipeline(
    gpu_proc: u8,
    gpu_channel_idx: usize,
    gpu_pa: u64,
    gpu_irq: u32,
    input_proc: Option<(u8, usize, u64, u32)>, // (proc, ch_idx, pa, irq)
    font_buf: Option<(u64, u32)>,              // (pa, len) from 9p read
    next_channel: &mut usize,
) {
    sys::print(b"     setting up display pipeline\n");

    // Allocate double framebuffer via DMA (two separate allocations for
    // front + back buffers). Each buffer is FB_SIZE bytes. We allocate
    // separately because the maximum DMA order is 10 (4 MiB) and a
    // single 2× allocation would exceed that.
    let fb_bytes = FB_SIZE as usize;
    let fb_pages = (fb_bytes + 4095) / 4096;
    let fb_order = (fb_pages.next_power_of_two().trailing_zeros()) as u32;
    let fb_alloc_bytes = (1usize << fb_order) * 4096;
    // Front buffer (buffer 0).
    let mut fb_pa0: u64 = 0;
    let fb_va0 = sys::dma_alloc(fb_order, &mut fb_pa0).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (framebuffer 0) failed\n");
        sys::exit();
    });

    unsafe { core::ptr::write_bytes(fb_va0 as *mut u8, 0, fb_alloc_bytes) };

    // Back buffer (buffer 1).
    let mut fb_pa1: u64 = 0;
    let fb_va1 = sys::dma_alloc(fb_order, &mut fb_pa1).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (framebuffer 1) failed\n");
        sys::exit();
    });

    unsafe { core::ptr::write_bytes(fb_va1 as *mut u8, 0, fb_alloc_bytes) };

    sys::print(b"     double framebuffer: ");

    print_u32(FB_WIDTH);

    sys::print(b"x");

    print_u32(FB_HEIGHT);

    sys::print(b" x2 (");

    print_u32((fb_alloc_bytes * 2) as u32 / 1024);

    sys::print(b" KiB)\n");

    // -----------------------------------------------------------------------
    // Send GPU config via ring buffer (on init↔GPU channel).
    // -----------------------------------------------------------------------
    let gpu_ch = init_channel(gpu_channel_idx);
    let gpu_config = GpuConfig {
        mmio_pa: gpu_pa,
        irq: gpu_irq,
        _pad: 0,
        fb_pa: fb_pa0,
        fb_pa2: fb_pa1,
        fb_width: FB_WIDTH,
        fb_height: FB_HEIGHT,
        fb_size: FB_SIZE,
        _pad2: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_GPU_CONFIG, &gpu_config) };

    gpu_ch.send(&msg);

    // -----------------------------------------------------------------------
    // Allocate shared document buffer (1 page).
    // Compositor gets read-write (sole writer), editor gets read-only.
    // -----------------------------------------------------------------------
    let mut doc_pa: u64 = 0;
    let _doc_va = sys::dma_alloc(0, &mut doc_pa).unwrap_or_else(|_| {
        sys::print(b"init: dma_alloc (doc buffer) failed\n");
        sys::exit();
    });

    unsafe { core::ptr::write_bytes(_doc_va as *mut u8, 0, 4096) };

    sys::print(b"     document buffer: 4 KiB shared\n");

    // -----------------------------------------------------------------------
    // Spawn compositor.
    // -----------------------------------------------------------------------
    let (comp_proc, _comp_ch_handle, comp_channel_idx) =
        match spawn_with_channel(COMPOSITOR_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn compositor\n");
                sys::exit();
            }
        };
    // Share both framebuffers with compositor (read-write).
    let fb_page_count = fb_alloc_bytes as u64 / 4096;
    let comp_fb_va0 =
        sys::memory_share(comp_proc, fb_pa0, fb_page_count, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (compositor fb0) failed\n");
            sys::exit();
        });
    let comp_fb_va1 =
        sys::memory_share(comp_proc, fb_pa1, fb_page_count, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (compositor fb1) failed\n");
            sys::exit();
        });
    // Share document buffer with compositor (read-write — sole writer).
    let comp_doc_va =
        sys::memory_share(comp_proc, doc_pa, DOC_BUF_PAGES, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (compositor doc) failed\n");
            sys::exit();
        });
    // Share font buffer with compositor (read-only) if available.
    let (comp_font_va, font_len) = if let Some((font_pa, flen)) = font_buf {
        let font_pages = ((flen as u64) + 4095) / 4096;
        let va = sys::memory_share(comp_proc, font_pa, font_pages, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (compositor font) failed\n");
            sys::exit();
        });

        (va as u64, flen)
    } else {
        (0u64, 0u32)
    };
    // Send compositor config via ring buffer.
    let comp_ch = init_channel(comp_channel_idx);
    let comp_config = CompositorConfig {
        fb_va: comp_fb_va0 as u64,
        fb_va2: comp_fb_va1 as u64,
        fb_width: FB_WIDTH,
        fb_height: FB_HEIGHT,
        fb_stride: FB_STRIDE,
        fb_size: FB_SIZE,
        doc_va: comp_doc_va as u64,
        doc_capacity: DOC_BUF_CAPACITY,
        font_len,
        font_va: comp_font_va,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_COMPOSITOR_CONFIG, &comp_config) };

    comp_ch.send(&msg);

    // -----------------------------------------------------------------------
    // Create cross-process channels.
    // -----------------------------------------------------------------------

    // Input → Compositor channel (keyboard events).
    // Endpoint A (send) → input driver, Endpoint B (recv) → compositor.
    if let Some((input_proc_handle, input_ch_idx, input_pa, input_irq)) = input_proc {
        sys::print(b"     creating input\xE2\x86\x92compositor channel\n");

        let (ic_a, ic_b) = sys::channel_create().unwrap_or_else(|_| {
            sys::print(b"init: channel_create (input-comp) failed\n");
            sys::exit();
        });

        *next_channel += 1; // channel_create advances init's SHM pointer

        // Send endpoint A to input driver (handle 1 in input's table).
        sys::handle_send(input_proc_handle, ic_a).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-comp A) failed\n");
            sys::exit();
        });
        // Send endpoint B to compositor (handle 1 in compositor's table).
        sys::handle_send(comp_proc, ic_b).unwrap_or_else(|_| {
            sys::print(b"init: handle_send (input-comp B) failed\n");
            sys::exit();
        });

        // Send input driver config via ring buffer.
        let input_ch = init_channel(input_ch_idx);
        let input_config = DeviceConfig {
            mmio_pa: input_pa,
            irq: input_irq,
            _pad: 0,
        };
        let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &input_config) };

        input_ch.send(&msg);
    }

    // Compositor → GPU channel (present commands).
    // Endpoint A (send) → compositor, Endpoint B (recv) → GPU driver.
    sys::print(b"     creating compositor\xE2\x86\x92gpu channel\n");

    let (cg_a, cg_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (comp-gpu) failed\n");
        sys::exit();
    });

    *next_channel += 1; // channel_create advances init's SHM pointer

    // Send endpoint A to compositor (handle 2 in compositor's table, or 1 if no input).
    sys::handle_send(comp_proc, cg_a).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (comp-gpu A) failed\n");
        sys::exit();
    });
    // Send endpoint B to GPU driver (handle 1 in GPU's table).
    sys::handle_send(gpu_proc, cg_b).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (comp-gpu B) failed\n");
        sys::exit();
    });

    // -----------------------------------------------------------------------
    // Compositor ↔ Editor channel.
    // The compositor (OS service) routes input to the editor and receives
    // write requests back. The editor never writes to the document directly.
    // -----------------------------------------------------------------------
    sys::print(b"     spawning text editor\n");

    let (editor_proc, _editor_ch, editor_ch_idx) =
        match spawn_with_channel(TEXT_EDITOR_ELF, next_channel) {
            Some(v) => v,
            None => {
                sys::print(b"init: failed to spawn text editor\n");
                sys::exit();
            }
        };
    // Share document buffer with editor (read-only — hardware-enforced).
    let editor_doc_va =
        sys::memory_share(editor_proc, doc_pa, DOC_BUF_PAGES, true).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (editor doc ro) failed\n");
            sys::exit();
        });
    // Send editor config via ring buffer.
    let editor_ch = init_channel(editor_ch_idx);
    let editor_config = EditorConfig {
        doc_va: editor_doc_va as u64,
        doc_capacity: DOC_BUF_CAPACITY,
        _pad: 0,
    };
    let msg = unsafe { ipc::Message::from_payload(MSG_EDITOR_CONFIG, &editor_config) };

    editor_ch.send(&msg);

    sys::print(b"     creating compositor\xE2\x86\x94editor channel\n");

    let (ce_a, ce_b) = sys::channel_create().unwrap_or_else(|_| {
        sys::print(b"init: channel_create (comp-editor) failed\n");
        sys::exit();
    });

    *next_channel += 1; // channel_create advances init's SHM pointer

    // Endpoint A (send/recv) → compositor (handle 3 in compositor's table).
    sys::handle_send(comp_proc, ce_a).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (comp-editor A) failed\n");
        sys::exit();
    });
    // Endpoint B (send/recv) → editor (handle 1 in editor's table).
    sys::handle_send(editor_proc, ce_b).unwrap_or_else(|_| {
        sys::print(b"init: handle_send (comp-editor B) failed\n");
        sys::exit();
    });

    // -----------------------------------------------------------------------
    // Start all processes. Order: GPU first (does device setup then waits),
    // input driver (does setup then waits for IRQs), editor (waits for
    // input), compositor last (draws initial frame then enters event loop).
    // -----------------------------------------------------------------------
    sys::print(b"     starting gpu driver\n");

    let _ = sys::process_start(gpu_proc);

    if let Some((input_proc_handle, _, _, _)) = input_proc {
        sys::print(b"     starting input driver\n");

        let _ = sys::process_start(input_proc_handle);
    }

    sys::print(b"     starting text editor\n");

    let _ = sys::process_start(editor_proc);

    sys::print(b"     starting compositor\n");

    let _ = sys::process_start(comp_proc);

    sys::print(b"     display pipeline running (with editor separation)\n");
}
/// Spawn a suspended process, create a channel to it, and send one endpoint.
///
/// Returns (process_handle, init_channel_handle, channel_index) on success.
/// The child receives endpoint B at CHANNEL_SHM_BASE in its address space.
/// Init retains endpoint A at channel_shm_va(channel_index).
fn spawn_with_channel(elf: &[u8], next_channel: &mut usize) -> Option<(u8, u8, usize)> {
    sys::print(b"       process_create\xE2\x80\xA6");

    let proc_handle = match sys::process_create(elf.as_ptr(), elf.len()) {
        Ok(h) => h,
        Err(_) => {
            sys::print(b" FAILED\n");
            return None;
        }
    };

    sys::print(b" ok\n");
    sys::print(b"       channel_create\xE2\x80\xA6");

    let (ch_a, ch_b) = match sys::channel_create() {
        Ok(pair) => pair,
        Err(_) => {
            sys::print(b" FAILED\n");
            return None;
        }
    };

    sys::print(b" ok\n");
    sys::print(b"       handle_send\xE2\x80\xA6");

    if let Err(_) = sys::handle_send(proc_handle, ch_b) {
        sys::print(b" FAILED\n");

        return None;
    }

    sys::print(b" ok\n");

    let channel_idx = *next_channel;

    *next_channel += 1;

    Some((proc_handle, ch_a, channel_idx))
}

#[unsafe(no_mangle)]
pub extern "C" fn _start() -> ! {
    sys::print(b"  \xF0\x9F\x94\xA7 init - proto-os-service starting\n");

    // Kernel channel (channel 0) uses raw bytes — kernel writes directly.
    let kernel_shm = CHANNEL_SHM_BASE as *const u8;
    let device_count = unsafe { core::ptr::read_volatile(kernel_shm as *const u32) };

    sys::print(b"     ");

    print_u32(device_count);

    sys::print(b" devices in manifest\n");

    // Track channel allocation (0 = kernel, 1+ = ours).
    let mut next_channel: usize = 1;
    // Saved device state for Phase 2 (display pipeline).
    let mut gpu: Option<(u8, u8, usize, u64, u32)> = None; // (proc, ch, ch_idx, pa, irq)
    let mut input: Option<(u8, usize, u64, u32)> = None; // (proc, ch_idx, pa, irq)
    let mut p9: Option<(u8, u8, usize, u64, u32)> = None; // (proc, ch, ch_idx, pa, irq)

    // Phase 1: Spawn a driver for each device in the manifest.
    let actual = if device_count > 8 { 8 } else { device_count };

    for i in 0..actual as usize {
        let base = unsafe { kernel_shm.add(8 + i * 16) };
        let dev_pa = unsafe { core::ptr::read_volatile(base as *const u64) };
        let dev_irq = unsafe { core::ptr::read_volatile(base.add(8) as *const u32) };
        let dev_id = unsafe { core::ptr::read_volatile(base.add(12) as *const u32) };

        sys::print(b"     device ");

        print_u32(i as u32);

        sys::print(b": id=");

        print_u32(dev_id);

        sys::print(b"\n");

        let elf: &[u8] = match dev_id {
            VIRTIO_DEVICE_BLK => VIRTIO_BLK_ELF,
            VIRTIO_DEVICE_CONSOLE => VIRTIO_CONSOLE_ELF,
            VIRTIO_DEVICE_GPU => VIRTIO_GPU_ELF,
            VIRTIO_DEVICE_INPUT => VIRTIO_INPUT_ELF,
            VIRTIO_DEVICE_9P => VIRTIO_9P_ELF,
            _ => {
                sys::print(b"     skipping unknown device id=");
                print_u32(dev_id);
                sys::print(b"\n");
                continue;
            }
        };

        sys::print(b"     spawning driver (elf ");

        print_u32(elf.len() as u32);

        sys::print(b" bytes)\n");

        let (proc_h, ch_h, channel_idx) = match spawn_with_channel(elf, &mut next_channel) {
            Some(v) => v,
            None => continue,
        };

        match dev_id {
            VIRTIO_DEVICE_GPU => {
                // Defer GPU startup — needs framebuffer and cross-process channels.
                gpu = Some((proc_h, ch_h, channel_idx, dev_pa, dev_irq));
            }
            VIRTIO_DEVICE_INPUT => {
                // Defer input startup — needs cross-process channel to compositor.
                input = Some((proc_h, channel_idx, dev_pa, dev_irq));
            }
            VIRTIO_DEVICE_9P => {
                // Defer 9p startup — font read must complete before compositor.
                p9 = Some((proc_h, ch_h, channel_idx, dev_pa, dev_irq));
            }
            _ => {
                // Start simple drivers (blk, console) immediately.
                let ch = init_channel(channel_idx);
                let config = DeviceConfig {
                    mmio_pa: dev_pa,
                    irq: dev_irq,
                    _pad: 0,
                };
                let msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &config) };

                ch.send(&msg);

                let _ = sys::process_start(proc_h);
                let name = match dev_id {
                    VIRTIO_DEVICE_BLK => "blk",
                    VIRTIO_DEVICE_CONSOLE => "console",
                    _ => "?",
                };

                sys::print(b"     spawned driver: ");
                sys::print(name.as_bytes());
                sys::print(b"\n");
            }
        }
    }

    // Phase 1.5: Read font file from host via 9p driver (must complete before compositor).
    // Phase 1.5: Start 9p driver, read font from host, pass to compositor.
    let font_buf: Option<(u64, u32)> = if let Some((p9_proc, p9_ch, p9_ch_idx, p9_pa, p9_irq)) = p9
    {
        sys::print(b"     loading font from host filesystem\n");

        // Allocate font buffer (16 KiB).
        let mut font_pa: u64 = 0;
        let _font_va = sys::dma_alloc(2, &mut font_pa).unwrap_or_else(|_| {
            sys::print(b"init: dma_alloc (font buffer) failed\n");
            sys::exit();
        });
        let font_capacity: u32 = 4 * 4096;

        unsafe { core::ptr::write_bytes(_font_va as *mut u8, 0, font_capacity as usize) };

        // Share font buffer with 9p driver (read-write).
        let p9_font_va = sys::memory_share(p9_proc, font_pa, 4, false).unwrap_or_else(|_| {
            sys::print(b"init: memory_share (9p font) failed\n");
            sys::exit();
        });
        // Send device config via IPC.
        let p9_ch_obj = init_channel(p9_ch_idx);
        let dev_config = DeviceConfig {
            mmio_pa: p9_pa,
            irq: p9_irq,
            _pad: 0,
        };
        let cfg_msg = unsafe { ipc::Message::from_payload(MSG_DEVICE_CONFIG, &dev_config) };

        p9_ch_obj.send(&cfg_msg);

        // Build font read request. Construct the message manually to avoid
        // any alignment issues with from_payload on a 60-byte struct.
        let mut req_msg = ipc::Message::new(MSG_FS_READ_REQUEST);

        unsafe {
            let p = req_msg.payload.as_mut_ptr();

            core::ptr::write_unaligned(p as *mut u64, p9_font_va as u64);
            core::ptr::write_unaligned(p.add(8) as *mut u32, font_capacity);
            core::ptr::write_unaligned(p.add(12) as *mut u32, 0); // _pad

            let name = b"SourceCodePro-Regular.ttf";

            core::ptr::copy_nonoverlapping(name.as_ptr(), p.add(16), name.len());
        }

        p9_ch_obj.send(&req_msg);

        // Start 9p driver and wait for font read completion.
        sys::print(b"     starting 9p driver\n");

        let _ = sys::process_start(p9_proc);
        let _ = sys::channel_signal(p9_ch);

        // Wait for font read response. The 9p driver needs time to negotiate
        // the protocol and read the file, so loop until a response arrives.
        sys::print(b"     waiting for font read\n");

        let mut resp_msg = ipc::Message::new(0);
        let result = loop {
            let _ = sys::wait(&[p9_ch], u64::MAX);

            if p9_ch_obj.try_recv(&mut resp_msg) && resp_msg.msg_type == MSG_FS_READ_RESPONSE {
                break Some(resp_msg);
            }
        };

        if let Some(resp_msg) = result {
            let (len, status) = unsafe {
                let p = resp_msg.payload.as_ptr();
                let len = core::ptr::read_unaligned(p as *const u32);
                let status = core::ptr::read_unaligned(p.add(4) as *const u32);

                (len, status)
            };

            if status == 0 && len > 0 {
                sys::print(b"     font loaded: ");

                print_u32(len);

                sys::print(b" bytes\n");

                Some((font_pa, len))
            } else {
                sys::print(b"     font read failed (status=");

                print_u32(status);

                sys::print(b")\n");

                None
            }
        } else {
            None
        }
    } else {
        None
    };

    // Phase 2: Display pipeline (input driver + compositor + GPU driver).
    if let Some((gpu_proc, _gpu_ch, gpu_channel_idx, gpu_pa, gpu_irq)) = gpu {
        setup_display_pipeline(
            gpu_proc,
            gpu_channel_idx,
            gpu_pa,
            gpu_irq,
            input,
            font_buf,
            &mut next_channel,
        );
    } else {
        sys::print(b"     no gpu found\n");
    }

    // If no GPU device was found, run headless tests.
    if gpu.is_none() {
        sys::print(b"     no gpu found, running headless tests\n");

        // Fuzz test — adversarial syscall testing.
        match sys::process_create(FUZZ_ELF.as_ptr(), FUZZ_ELF.len()) {
            Ok(proc_h) => {
                let _ = sys::process_start(proc_h);
                let _ = sys::wait(&[proc_h], u64::MAX);
            }
            Err(_) => {
                sys::print(b"     fuzz test spawn failed\n");
            }
        }
        // Stress test — IPC/scheduler/timer saturation.
        match sys::process_create(STRESS_ELF.as_ptr(), STRESS_ELF.len()) {
            Ok(proc_h) => {
                let _ = sys::process_start(proc_h);
                let _ = sys::wait(&[proc_h], u64::MAX);
            }
            Err(_) => {
                sys::print(b"     stress test spawn failed\n");
            }
        }
    }

    sys::print(b"  \xF0\x9F\x94\xA7 init - running (idle)\n");

    // Don't exit — child processes are still running their event loops.
    // Idle forever via yield. In the real OS, init would become the OS
    // service process (renderer, metadata DB, input router, compositor).
    loop {
        sys::yield_now();
    }
}
