//! PNG decoder tests.

#[path = "../../services/decoders/png/png.rs"]
mod png;
use png::{png_decode, png_header, PngError};

// ---------------------------------------------------------------------------
// Test data
// ---------------------------------------------------------------------------

// 4x4 RGBA test PNG (filter=None, generated by Python)
const TEST_PNG_4X4_RGBA: &[u8] = &[
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x04, 0x08, 0x06, 0x00, 0x00, 0x00, 0xa9, 0xf1, 0x9e,
    0x7e, 0x00, 0x00, 0x00, 0x30, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x2d, 0x8b, 0xc9, 0x11, 0x00,
    0x30, 0x08, 0x02, 0xb7, 0x34, 0x4b, 0xdb, 0xd2, 0xec, 0x8c, 0xa8, 0x13, 0xe0, 0xc1, 0x70, 0x10,
    0xc8, 0x91, 0x1c, 0x60, 0x1d, 0x38, 0x91, 0x63, 0xa5, 0xaa, 0xa2, 0xa6, 0xbb, 0x77, 0x20, 0x5f,
    0x73, 0x72, 0x0a, 0xf2, 0x00, 0x81, 0x4b, 0x23, 0xe6, 0xa6, 0x81, 0xd8, 0x2d, 0x00, 0x00, 0x00,
    0x00, 0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
];

// 4x4 RGB test PNG (filter=None, generated by Python)
const TEST_PNG_4X4_RGB: &[u8] = &[
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x04, 0x08, 0x02, 0x00, 0x00, 0x00, 0x26, 0x93, 0x09,
    0x29, 0x00, 0x00, 0x00, 0x28, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0xf8, 0xcf, 0xc0, 0xc0,
    0x00, 0xc6, 0x40, 0x00, 0xa4, 0x18, 0x1a, 0xe0, 0xd8, 0xc1, 0xc1, 0xa1, 0xa1, 0xa1, 0xe1, 0xc0,
    0x81, 0x03, 0x20, 0x89, 0xff, 0x0d, 0x40, 0x91, 0xff, 0x40, 0x0a, 0x88, 0x01, 0xd6, 0x80, 0x14,
    0x74, 0x98, 0xeb, 0xef, 0xc4, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60,
    0x82,
];

// 4x5 RGBA test PNG with all 5 filter types (None, Sub, Up, Average, Paeth)
const TEST_PNG_ALL_FILTERS: &[u8] = &[
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x05, 0x08, 0x06, 0x00, 0x00, 0x00, 0x62, 0xad, 0x4d,
    0xdb, 0x00, 0x00, 0x00, 0x3f, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x38, 0x61, 0x24, 0xf7,
    0x1f, 0x19, 0x33, 0x1a, 0xa5, 0x04, 0xfc, 0xb7, 0x61, 0x60, 0x60, 0x80, 0x61, 0x26, 0x2e, 0x2e,
    0x2e, 0x06, 0x64, 0xcc, 0xec, 0xf6, 0xdb, 0xdb, 0xf3, 0x9b, 0x08, 0xff, 0xd3, 0x1b, 0xba, 0xfc,
    0x4f, 0x77, 0xb9, 0xf1, 0x3f, 0x65, 0x79, 0x23, 0xb7, 0xeb, 0x0d, 0xc3, 0x1b, 0x23, 0x06, 0x86,
    0x5d, 0x10, 0x0c, 0x00, 0x39, 0x9f, 0x18, 0xde, 0xbc, 0x00, 0x72, 0x5f, 0x00, 0x00, 0x00, 0x00,
    0x49, 0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
];

// ---------------------------------------------------------------------------
// PNG header parsing
// ---------------------------------------------------------------------------

#[test]
fn png_header_parses_rgba() {
    let hdr = png_header(TEST_PNG_4X4_RGBA).unwrap();
    assert_eq!(hdr.width, 4);
    assert_eq!(hdr.height, 4);
    assert_eq!(hdr.bit_depth, 8);
    assert_eq!(hdr.color_type, 6); // RGBA
}

#[test]
fn png_header_parses_rgb() {
    let hdr = png_header(TEST_PNG_4X4_RGB).unwrap();
    assert_eq!(hdr.width, 4);
    assert_eq!(hdr.height, 4);
    assert_eq!(hdr.bit_depth, 8);
    assert_eq!(hdr.color_type, 2); // RGB
}

#[test]
fn png_header_parses_all_filters() {
    let hdr = png_header(TEST_PNG_ALL_FILTERS).unwrap();
    assert_eq!(hdr.width, 4);
    assert_eq!(hdr.height, 5);
    assert_eq!(hdr.bit_depth, 8);
    assert_eq!(hdr.color_type, 6); // RGBA
}

#[test]
fn png_invalid_magic_returns_err() {
    let bad_data = [0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08];
    let result = png_header(&bad_data);
    assert_eq!(result.unwrap_err(), PngError::InvalidSignature);
}

#[test]
fn png_decode_invalid_magic_returns_err() {
    let bad_data = [0x00; 64];
    let mut output = [0u8; 256];
    let result = png_decode(&bad_data, &mut output);
    assert_eq!(result.unwrap_err(), PngError::InvalidSignature);
}

#[test]
fn png_truncated_before_signature_returns_err() {
    let data = &[0x89, 0x50, 0x4e];
    assert_eq!(png_header(data).unwrap_err(), PngError::Truncated);
}

#[test]
fn png_truncated_ihdr_returns_err() {
    let data = &TEST_PNG_4X4_RGBA[..20];
    assert_eq!(png_header(data).unwrap_err(), PngError::Truncated);
}

#[test]
fn png_truncated_idat_returns_err() {
    let data = &TEST_PNG_4X4_RGBA[..50];
    let mut output = [0u8; 4 * 4 * 4 + 4];
    let result = png_decode(data, &mut output);
    assert!(result.is_err(), "truncated IDAT should return Err");
}

#[test]
fn png_zero_width_returns_err() {
    let mut bad_png = TEST_PNG_4X4_RGBA.to_vec();
    bad_png[16] = 0;
    bad_png[17] = 0;
    bad_png[18] = 0;
    bad_png[19] = 0;
    assert_eq!(png_header(&bad_png).unwrap_err(), PngError::ZeroDimensions);
}

#[test]
fn png_zero_height_returns_err() {
    let mut bad_png = TEST_PNG_4X4_RGBA.to_vec();
    bad_png[20] = 0;
    bad_png[21] = 0;
    bad_png[22] = 0;
    bad_png[23] = 0;
    assert_eq!(png_header(&bad_png).unwrap_err(), PngError::ZeroDimensions);
}

#[test]
fn png_unsupported_bit_depth_returns_err() {
    let mut bad_png = TEST_PNG_4X4_RGBA.to_vec();
    bad_png[24] = 16;
    let mut output = [0u8; 4 * 4 * 4 + 4];
    assert_eq!(
        png_decode(&bad_png, &mut output).unwrap_err(),
        PngError::UnsupportedFormat
    );
}

#[test]
fn png_unsupported_color_type_returns_err() {
    let mut bad_png = TEST_PNG_4X4_RGBA.to_vec();
    bad_png[25] = 4;
    let mut output = [0u8; 4 * 4 * 4 + 4];
    assert_eq!(
        png_decode(&bad_png, &mut output).unwrap_err(),
        PngError::UnsupportedFormat
    );
}

#[test]
fn png_unsupported_color_type_grayscale_returns_err() {
    let mut bad_png = TEST_PNG_4X4_RGBA.to_vec();
    bad_png[25] = 0;
    let mut output = [0u8; 4 * 4 * 4 + 4];
    assert_eq!(
        png_decode(&bad_png, &mut output).unwrap_err(),
        PngError::UnsupportedFormat
    );
}

#[test]
fn png_decode_rgba_4x4_pixel_values() {
    let mut output = [0u8; 128];
    let hdr = png_decode(TEST_PNG_4X4_RGBA, &mut output).unwrap();
    assert_eq!(hdr.width, 4);
    assert_eq!(hdr.height, 4);

    let px = &output[0..4];
    assert_eq!(px[0], 0);
    assert_eq!(px[1], 0);
    assert_eq!(px[2], 255);
    assert_eq!(px[3], 255);

    let px = &output[4..8];
    assert_eq!(px[0], 0);
    assert_eq!(px[1], 255);
    assert_eq!(px[2], 0);
    assert_eq!(px[3], 255);

    let px = &output[8..12];
    assert_eq!(px[0], 255);
    assert_eq!(px[1], 0);
    assert_eq!(px[2], 0);
    assert_eq!(px[3], 255);

    let px = &output[12..16];
    assert_eq!(px, &[255, 255, 255, 255]);

    let row1_start = 4 * 4;
    let px = &output[row1_start + 4..row1_start + 8];
    assert_eq!(px[0], 0);
    assert_eq!(px[1], 0);
    assert_eq!(px[2], 255);
    assert_eq!(px[3], 128);
}

#[test]
fn png_decode_rgb_4x4_pixel_values() {
    let mut output = [0u8; 128];
    let hdr = png_decode(TEST_PNG_4X4_RGB, &mut output).unwrap();
    assert_eq!(hdr.width, 4);
    assert_eq!(hdr.height, 4);

    let px = &output[0..4];
    assert_eq!(px[0], 0);
    assert_eq!(px[1], 0);
    assert_eq!(px[2], 255);
    assert_eq!(px[3], 255);

    let px = &output[4..8];
    assert_eq!(px[0], 0);
    assert_eq!(px[1], 255);
    assert_eq!(px[2], 0);
    assert_eq!(px[3], 255);

    let px = &output[8..12];
    assert_eq!(px[0], 255);
    assert_eq!(px[1], 0);
    assert_eq!(px[2], 0);
    assert_eq!(px[3], 255);

    let row1_start = 4 * 4;
    let px = &output[row1_start + 12..row1_start + 16];
    assert_eq!(px[0], 128);
    assert_eq!(px[1], 0);
    assert_eq!(px[2], 0);
    assert_eq!(px[3], 255);
}

#[test]
fn png_decode_all_filter_types() {
    let mut output = [0u8; 256];
    let hdr = png_decode(TEST_PNG_ALL_FILTERS, &mut output).unwrap();
    assert_eq!(hdr.width, 4);
    assert_eq!(hdr.height, 5);

    fn check_pixel(output: &[u8], row: usize, col: usize, r: u8, g: u8, b: u8, a: u8) {
        let stride = 4 * 4;
        let offset = row * stride + col * 4;
        assert_eq!(output[offset], b, "pixel ({},{}) B", col, row);
        assert_eq!(output[offset + 1], g, "pixel ({},{}) G", col, row);
        assert_eq!(output[offset + 2], r, "pixel ({},{}) R", col, row);
        assert_eq!(output[offset + 3], a, "pixel ({},{}) A", col, row);
    }

    check_pixel(&output, 0, 0, 200, 50, 30, 255);
    check_pixel(&output, 0, 1, 200, 50, 30, 255);
    check_pixel(&output, 0, 2, 200, 50, 30, 255);
    check_pixel(&output, 0, 3, 200, 50, 30, 255);

    check_pixel(&output, 1, 0, 50, 100, 80, 255);
    check_pixel(&output, 1, 1, 110, 100, 80, 255);
    check_pixel(&output, 1, 2, 170, 100, 80, 255);
    check_pixel(&output, 1, 3, 230, 100, 80, 255);

    check_pixel(&output, 2, 0, 60, 110, 90, 255);
    check_pixel(&output, 2, 1, 120, 110, 90, 255);
    check_pixel(&output, 2, 2, 180, 110, 90, 255);
    check_pixel(&output, 2, 3, 240, 110, 90, 255);

    check_pixel(&output, 3, 0, 100, 50, 120, 200);
    check_pixel(&output, 3, 1, 100, 100, 120, 200);
    check_pixel(&output, 3, 2, 100, 150, 120, 200);
    check_pixel(&output, 3, 3, 100, 200, 120, 200);

    check_pixel(&output, 4, 0, 80, 80, 50, 180);
    check_pixel(&output, 4, 1, 80, 80, 100, 180);
    check_pixel(&output, 4, 2, 80, 80, 150, 180);
    check_pixel(&output, 4, 3, 80, 80, 200, 180);
}

#[test]
fn png_decode_buffer_too_small_returns_err() {
    let mut output = [0u8; 16];
    let result = png_decode(TEST_PNG_4X4_RGBA, &mut output);
    assert_eq!(result.unwrap_err(), PngError::BufferTooSmall);
}

#[test]
fn png_empty_data_returns_err() {
    let result = png_header(&[]);
    assert_eq!(result.unwrap_err(), PngError::Truncated);
}

#[test]
fn png_decode_empty_data_returns_err() {
    let mut output = [0u8; 256];
    let result = png_decode(&[], &mut output);
    assert_eq!(result.unwrap_err(), PngError::Truncated);
}

#[test]
fn png_decode_test_image_from_file() {
    let data = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/../share/test.png"));
    if let Ok(data) = data {
        let hdr = png_header(&data).unwrap();
        assert!(hdr.width > 0 && hdr.height > 0);
        assert_eq!(hdr.bit_depth, 8);
        assert!(hdr.color_type == 2 || hdr.color_type == 6);

        let channels: usize = if hdr.color_type == 6 { 4 } else { 3 };
        let scanline_bytes = 1 + hdr.width as usize * channels;
        let raw_size = scanline_bytes * hdr.height as usize;
        let out_size = (hdr.width * hdr.height * 4) as usize;
        let buf_size = if raw_size > out_size {
            raw_size
        } else {
            out_size
        };
        let mut output = vec![0u8; buf_size];
        let result = png_decode(&data, &mut output);
        assert!(
            result.is_ok(),
            "failed to decode test.png: {:?}",
            result.unwrap_err()
        );

        let a = output[3];
        assert!(a > 0, "pixel (0,0) alpha should be > 0, got {}", a);

        let cx = hdr.width / 2;
        let cy = hdr.height / 2;
        let center = (cy as usize * hdr.width as usize + cx as usize) * 4;
        let center_a = output[center + 3];
        assert!(center_a > 0, "center pixel alpha should be > 0");
    }
}

#[test]
fn png_decode_to_surface_correct_colors() {
    let data = std::fs::read(concat!(env!("CARGO_MANIFEST_DIR"), "/../share/test.png"));
    if let Ok(data) = data {
        let hdr = png_header(&data).unwrap();
        let channels: usize = if hdr.color_type == 6 { 4 } else { 3 };
        let scanline_bytes = 1 + hdr.width as usize * channels;
        let raw_size = scanline_bytes * hdr.height as usize;
        let out_size = (hdr.width * hdr.height * 4) as usize;
        let buf_size = if raw_size > out_size {
            raw_size
        } else {
            out_size
        };
        let mut output = vec![0u8; buf_size];
        let _ = png_decode(&data, &mut output).unwrap();

        let mut non_zero = 0;
        for i in 0..(hdr.width * hdr.height) as usize {
            let r = output[i * 4 + 2];
            let g = output[i * 4 + 1];
            let b = output[i * 4];
            if r > 0 || g > 0 || b > 0 {
                non_zero += 1;
            }
        }
        assert!(
            non_zero > 100,
            "decoded image should have many non-zero pixels, got {}",
            non_zero
        );

        let px00_r = output[2];
        let cx = hdr.width / 2;
        let cy = hdr.height / 2;
        let center = (cy as usize * hdr.width as usize + cx as usize) * 4;
        let px_center_r = output[center + 2];
        assert_ne!(px00_r, px_center_r, "corner and center should differ");
    }
}
