commands:
  build: cd /Users/user/Sites/os/system && cargo build --release
  test: cd /Users/user/Sites/os/system/test && cargo test -- --test-threads=1
  visual-test: cd /Users/user/Sites/os/system && bash test-qemu.sh
  smoke-test: cd /Users/user/Sites/os/system/test && bash smoke.sh
  stress-test: cd /Users/user/Sites/os/system/test && bash stress.sh
  integration-test: cd /Users/user/Sites/os/system/test && bash integration.sh
